#!/usr/bin/env python3
"""Comprehensive German notes_de translations with proper grammar."""

import json, glob

OUT = "drink_guide"

NOTES_DE = {
    # ── BEERS: Always on Tap (pages 2-5) ──
    "pub_beer_001": "Hell goldene Farbe, tropisches Aroma mit Noten von Grapefruit, Ananas und Litschi über Karamellmalz. Kräftige Zitrus- und Hopfenaromen, ausbalanciert durch leichte Karamellsüße und einen spitz-bitteren Abgang.",
    "pub_beer_002": "Trübes, gold-orangenes New England IPA mit saftig-tropischem Aroma von Zitrus, Mango und Maracuja. Weiche, saftige Noten dominieren bei minimaler Bitterkeit.",
    "pub_beer_003": "Tief schwarzes, irisches, trockenes Stout mit dezentem Kaffee- und Schokoladen-Aroma. Sanfter, gerösteter Malz-Geschmack, leicht bitter mit cremig-seidiger Kohlensäure.",
    "pub_beer_004": "Tief bernsteinfarbenes Brown Ale mit getoastetem Malz-Aroma, Karamell und dezenten nussigen Noten. Sanfte Toffee-Süße mit angenehm röstigem Abgang. Mittlerer Körper, sanfte Kohlensäure.",
    "pub_beer_005": "Klares, bernsteinfarben-goldenes, englisches Pale Ale. Malzig-süßes Aroma mit Keks-Noten und dezent blumigem Hopfen. Ausgewogener Malz- und Hopfen-Charakter mit Anklängen von Karamell. Mittlerer Körper, weicher, leicht süßer Abgang.",
    "pub_beer_006": "Tief rötlich-bernsteinfarbenes, irisches Red Ale mit malzigem Aroma, Anklängen von Karamell und getoastetem Brot. Weicher, süßer Malz-Geschmack mit nussigen und Toffee-Noten. Cremige Textur, weicher, süßer Abgang.",
    "pub_beer_007": "Klares, hellgoldenes Pils mit Keksmalz- und grasigem Hopfen-Aroma. Knackiger, malziger Geschmack, ausgewogen durch erdige Bitterkeit und einen leicht bitteren, trockenen Abgang.",
    "pub_beer_008": "Österreichisches Radler, hellgelb und leicht trüb. Spritziges Zitronen-Aroma, knackiger, spritziger Zitronengeschmack mit leichter Malzsüße und sanfter Kohlensäure. Alkoholarm, ohne künstliche Zusätze.",
    "pub_beer_009": "Goldgelbes Trappistenbier mit frischem, fruchtigem Aroma von Zitrus und Banane, ergänzt durch süßes Malz und dezente Gewürznoten. Leicht süß mit sanfter Bitterkeit und sauberem, erfrischendem Abgang.",
    "pub_beer_010": "Französisches Witbier, trüb und hellgolden. Anklänge von Zitrus und exotischen Früchten, leicht süß mit erfrischendem Zitrusprofil, ausgewogen durch sanfte Bitterkeit von Koriander und Hopfen. Cremig und prickelnd.",
    "pub_beer_011": "Doppelt gehopftes Lager aus der Guinness Open Gate Brewery. Gold-bernsteinfarben, leichtes, hopfiges Aroma mit blumigen und zitrusartigen Noten. Voller Geschmack, lebendiger, knackiger, erfrischender Abgang mit anhaltendem Hopfencharakter.",
    "pub_beer_012": "Italienisches, helles Lager, ausgewogen und weich mit brotigem Malzcharakter und dezenten Zitrus- und Blumennoten. Leichte Bitterkeit und knackiger Abgang.",
    "pub_beer_013": "Amerikanisches Amber Lager, goldene Farbe mit Karamell-Aroma, getoastetem Malz und blumigen Zitrusnoten. Ausgewogene Malzsüße mit Toffee und knackiger Hopfenbitterkeit. Mittlerer Körper, anhaltender Hopfenabgang.",
    "pub_beer_014": "Furchtloses IPA für alle. Unverhohlene Noten von Zitrusschale und Grapefruit, ein erfrischendes IPA, das Diversität zelebriert. Ausgewogen, knackig und hopfig.",
    "pub_beer_015": "Dänisches Lager, trüb und gold-bernsteinfarben. Leicht malziges Aroma mit Honig, Getreide und dezenten Zitrusnoten. Sanfter, süß-malziger Geschmack mit mäßig bitterem Abgang. Sauberer, leicht trockener Nachgeschmack.",
    "pub_beer_016": "Tschechisches, helles Lager mit Žatec-Hopfen und mährischer Gerste. Klares Gold-Bernstein, knackige, saubere Noten von frischem Brot und grasigem Hopfen mit Malzsüße. Mittlerer Körper, sauberer, trockener Abgang.",
    "pub_beer_017": "Beliebtes niederländisches Lager, hellgolden. Leichtes, malzig-süßes Aroma mit dezentem Getreide und blumigen Noten. Stark karbonisiert, sauber und knackig, leicht bitter. Extra kalt serviert.",
    "pub_beer_018": "Dortmunder Export, klares Gold-Bernstein. Leichtes, malzig-süßes Aroma mit dezentem Getreide und blumigen Noten. Ausgewogener, malzig-süßer Geschmack, knackiger, trockener Abgang mit leichter, anhaltender Hopfenbitterkeit.",
    "pub_beer_019": "Tschechisches, helles Lager, klares Gold. Mildes, malzig-süßes Aroma mit leichtem Brot und blumigen Noten. Ausgewogen und weich mit leicht süß-malzigem Geschmack und subtiler Bitterkeit. Sanfter Hopfennachgeschmack.",
    "pub_beer_020": "Belgisches Dubbel, tief bernsteinfarben mit rötlichen Reflexen. Karamell- und Toastbrot-Aroma mit Trockenfrüchten und leichter Würze. Reichhaltig malzig-süß mit Noten von Karamell und dunklen Früchten sowie milder Hopfenbitterkeit. Warmer, malziger, subtil trockener Abgang.",
    "pub_beer_021": "Bayerisches Helles Lager, hellgolden und klar. Leichtes, malzig-süßes Aroma mit dezenten, blumigen Hopfennoten. Sanfter, malzbetonter Geschmack mit sanfter Bitterkeit. Mittlerer Körper, weich karbonisiert, sauber, knackig und erfrischend.",
    "pub_beer_022": "Leichter, prickelnder, trockener, englischer Cidre — der beliebteste Cidre Großbritanniens. Helles Gold, klares Apfelaroma mit blumigen und zitrusartigen Anklängen. Knackig und trocken mit subtiler Süße und starkem Apfelcharakter.",
    "pub_beer_023": "Süßer Apfel-Cidre aus Dänemark. Golden und klar mit leichter Kohlensäure. Frisches, süßes Apfelaroma mit blumigen Anklängen. Süß und apfelbetont mit milder Säure.",
    "pub_beer_024": "Erstaunlich alkoholfrei. Leicht, hopfenverfeinert, fruchtig mit hopfigem Aroma.",

    # ── BEERS: Guest Taps (page 6) ──
    "pub_beer_025": "Wunderbar frisches IPA mit angenehmer Säure und weichem Malzkörper. Großzügige Mengen an Mosaic- und Citra-Hopfen.",
    "pub_beer_026": "Klares Gold mit leichtem Bernstein. Komplexes Zusammenspiel von Simcoe-, Strata-, Citra- und Magnum-Hopfen: tropische Früchte, Zitrus, Maracuja gepaart mit harzigen, erdigen Untertönen.",
    "pub_beer_027": "Spezielles, bernsteinfarbenes Spezialbier, gebraut nach dem klassischen Maischverfahren.",
    "pub_beer_028": "Kupfer-roségoldenes irisches Ale mit leichten, frischen Bier-Anklängen im Aroma. Dezente Fruchtigkeit von Rosinen ohne Süße. Milder, subtil bitterer, trockener Nachgeschmack.",
    "pub_beer_029": "Leicht herb und erfrischend, gefolgt von süßem, malzigem Maisgeschmack. Dezente Fruchtigkeit mit würzig-herben Noten. Sehr mild, keine Bitterkeit. Leicht, süffig, der perfekte Durstlöscher kalt serviert.",
    "pub_beer_030": "Lager nach Wiener Art. Sanfte Frucht- und dezente Hefenoten im Aroma. Harmonischer Malzkörper am Gaumen. Zurückhaltende Bitterkeit als Ausgleich mit weichem Abgang.",

    # ── BEERS: Alcohol Free (pages 7-10) ──
    "pub_beer_031": "Gold-bernsteinfarbenes, alkoholfreies Pale Ale. Frisches Zitrus-, erdiges Kräuter- und dezent süßes Aroma. Heller Zitrus-Geschmack mit Mandarine und Zitrone, leichte Malzsüße mit einem Hauch von Kiefer. Leichter Körper, knackig, prickelnd.",
    "pub_beer_032": "Alkoholfreies, deutsches Weizenbier. Strohgelb mit feinem Hefe- und dezentem Hopfen-Aroma. Reichhaltiger, malziger und würziger Geschmack mit einem Hauch fruchtiger Säure. Vollmundig und erfrischend.",
    "pub_beer_033": "Helles, goldfarbenes, klares, alkoholfreies Lager. Leichte Malzsüße mit dezenten Getreide- und Blumennoten. Milder Malzcharakter, sanfte Bitterkeit. Leichter Körper, weich, mäßig karbonisiert, erfrischend.",
    "pub_beer_034": "Alkoholfreies, helles Lager, hellgolden und klar. Leichtes, malzig-süßes Aroma mit Getreide- und Hopfennoten. Malzig und leicht süß mit sanfter Bitterkeit. Leichter Körper, weich, leicht karbonisiert.",
    "pub_beer_035": "Alkoholfreie Version des beliebten irischen Stouts.",
    "pub_beer_036": "Das weltweit erste alkoholfreie 0,0%-Trappistenbier. Dunkel bernsteinfarben mit cremigem, weißem Schaum. Fruchtig und malzig mit angenehmer Bitterkeit und karamell-süßem Abgang.",
    "pub_beer_037": "Alkoholfreies Juicy Pale Ale, inspiriert von Miami. Schmeckt nach Piña Colada — Ananas trifft auf Kokosnuss mit einem Hauch von rosa Grapefruit.",
    "pub_beer_038": "Das erste deutsche alkoholfreie India Pale Ale. Voller Geschmack trotz fehlendem Alkohol.",
    "pub_beer_039": "Dunkel bernsteinfarbenes, malziges und süßes Getränk. Traditionelles Malzerlebnis ohne Alkohol. Reichhaltiges Malz, Karamell und dezent süße Aromen, sauberer, leicht süßer Abgang. Vollgepackt mit Vitaminen, ein Naturprodukt.",
    "pub_beer_040": "Alkoholfreies Pale Ale, golden mit dezenter Trübung. Saftige, tropische Aromen von Ananas, Mango und Grapefruit, überlagert von grasig-kieferigen Hopfennoten. Hell und zitrusbetont, sauber und süffig.",
    "pub_beer_041": "Erfrischendes, goldenes, alkoholfreies, belgisches Blonde. Sanftes Getreide- und erdiges Aroma mit fruchtigen und würzigen Untertönen. Leicht, sanfte Helligkeit und knackiger, subtil kräuteriger Abgang.",
    "pub_beer_042": "Leicht goldenes, leicht trübes, alkoholfreies IPA. Ausgewogenes Aroma von süßem Malz und tropischen Früchten. Fruchtige Süße mit kräftiger Bitterkeit und erdig-kieferigen Noten. Langer, trockener, angenehm bitterer Abgang.",
    "pub_beer_043": "Alkoholfreie Version des Lindemans Kriek. Klassisches, fruchtiges Kirschbier ohne Alkohol.",
    "pub_beer_044": "Alkoholfreies Lager. Das vollständige Biergarten-Gefühl ohne den Kater.",
    "pub_beer_045": "Alles, was man an einem frischen, tropischen IPA liebt — nur ohne Alkohol. Leicht trüb und golden mit samtigem Mundgefühl durch Hafer und Weizen.",
    "pub_beer_046": "Das legendäre belgische Bier-Erlebnis ohne Alkohol. Würziges und fruchtiges Aroma, begleitet von leichter Bitterkeit. Klares Goldgelb mit feinporigem Schaum.",
    "pub_beer_047": "Zitrusnoten, trockener Abgang und trübes, ungefiltertes Erscheinungsbild. Ein einzigartiges Geschmackserlebnis ohne den typischen alkoholfreien Biercharakter.",
    "pub_beer_048": "Natürlich trübes, hellblondes Trappistenbier mit üppigem Schaum. Angenehme Bitterkeit und erfrischender Abgang.",
    "pub_beer_049": "Belgischer Biergenuss ohne Alkohol. Goldene Erscheinung, würzig-fruchtiges Aroma und sanfte Bitterkeit. Vollmundiges Craft Beer für bewussten Genuss.",
    "pub_beer_050": "Hazy AF hat allen Charakter und Geschmack — nur ohne Alkohol. Tropische Früchte treffen auf grasige Noten, Hafer und Weizen sorgen für samtiges Mundgefühl.",
    "pub_beer_051": "Belgisches, alkoholfreies Fruchtbier. Leuchtend kirschrote Farbe, rote Fruchtintensität — Kirschen, Himbeeren, Erdbeeren, Heidelbeeren und Holunderbeeren. Prickelnd und leicht, am besten On the Rocks zu genießen.",
    "pub_beer_052": "Überraschend vollmundig für ein alkoholfreies Bier. Leichte Malzsüße mit angenehm fruchtigem, mild-herbem Hopfenaroma, das an Pfirsich und Litschi erinnert.",
    "pub_beer_053": "Klares Gerstenbier ohne Nachgeschmack. Durch das beste Pressverfahren und die Erstpresswürze entsteht ein eleganter Geschmack mit weniger Geschmacksbeeinträchtigung.",
    "pub_beer_054": "Alkoholfreier, hellgoldener Cidre mit knackiger Apfelsüße und mildem, sauberem, erfrischendem Abgang.",
    "pub_beer_055": "Hergestellt aus selbst angebauten, frisch gepressten Cidre-Äpfeln. Alkoholarm mit süßem, aber frischem Geschmack.",
    "pub_beer_056": "Innovativer, alkoholfreier Cidre — eine Mischung aus Apfelwein und frischem Saft von nordirischen Tafeläpfeln. Strohgelb mit feiner Kohlensäure, leicht, erfrischend und halbtrocken. Nur 76 Kalorien.",
    "pub_beer_057": "Erfrischender Apfelgeschmack mit einer Balance aus fruchtigen und süßen Noten. 0% Alkohol, 0% Zucker, 0% Kalorien. Lang anhaltender, fruchtiger Geschmack.",

    # ── BEERS: Bottles - Ales (pages 11-14) ──
    "pub_beer_058": "Belgisches, starkes, helles Ale, hellgolden. Duftende Mischung aus Zitrusschale, Apfel, Banane und dezenten Gewürzen. Knackig und trocken mit heller Malzsüße. Seidig-weich mit lebendiger Kohlensäure.",
    "pub_beer_059": "Dunkelbraun mit rubinroten Reflexen, belgisches starkes Dunkelbier. Reichhaltige Noten von karamellisiertem Zucker, dunklen Früchten und einem Hauch von Banane. Süße Malzigkeit, mittlerer Körper, mäßige Kohlensäure. Sanft wärmend mit anhaltendem, malzig-süßem Abgang.",
    "pub_beer_060": "Auf Hawaii gebraut. Leichtes, malzig-süßes Aroma mit Anklängen tropischer Früchte. Knackig und erfrischend mit ausgewogenem Malzprofil und Honig- sowie Karamellnoten. Leichter Körper, weicher, sauberer Abgang.",
    "pub_beer_061": "Flämisches Rotbier, teilweise in Eichenholzfässern gereift. Komplexe Schichten von herben roten Früchten, Balsamico-Essig und Eiche, ausgewogen durch subtile Süße, ähnlich wie Madeira-Wein. Mittlerer Körper, lebendige Kohlensäure, trockener, herber Abgang.",
    "pub_beer_062": "Starkes Ale, gebraut in Kent. Tief bernsteinfarben mit rubinroten Reflexen. Reichhaltiges, malziges Aroma mit Karamell, Toffee und Trockenfrüchten. Vollmundig mit Pflaumen, getrockneten Aprikosen, Pfeffer und Zimt. Sauberer Abgang mit subtiler Blutorangen-Bitterkeit.",
    "pub_beer_063": "Scotch Ale mit klarem, bernsteinfarbenem Aussehen und orangefarbenen Reflexen. Reichhaltiges, malziges Aroma mit Karamell, Toffee und Trockenfrüchten. Dunkle Früchte und Gewürzanklänge. Weich, gut karbonisiert mit sauberem, subtil blutorangenem Abgang.",
    "pub_beer_064": "Golden Ale, ausgewogen durch Zitrusaromen und Anklänge von Hopfen und Malz. Perfekt abgestimmte Bitterkeit und angenehme Kohlensäure.",
    "pub_beer_065": "Sehr weicher Antrunk mit Toffee, Schokolade und dezenten fruchtigen Zitronennoten. Trockenfruchtaromen mit moderatem, bitterem Abgang.",
    "pub_beer_066": "Rundes und sehr vollmundiges Irish Red Ale, fast wie ein Bockbier. Karamellmalz kommt deutlich durch, der Hopfen sorgt für kräftigen Biss. Ein Red Ale mit starkem Charakter.",
    "pub_beer_067": "Reichhaltige Malznoten, ergänzt durch Trockenfrüchte — Rosinen und Pflaumen. Warmer Unterton von Nelken, Zimt und Muskatnuss, abgerundet durch eine subtile Hopfenbitterkeit für angenehme Frische.",
    "pub_beer_068": "Unwiderstehliches Golden Ale. Neue-Welt-Hopfen ergänzen das keksige, helle Malz. Durstlöschend mit Fruchtaromen von Zitrone, Aprikose und Pfirsich.",
    "pub_beer_069": "Ein kultiges Bier, der Goldstandard für handwerklich hergestellte, schottische Premium-Ales. Reife, fruchtige und Röstkaffee-Aromen mit Geschmacksnoten von dunkler Schokolade, Datteln und Nüssen aus Röstmalz und robustem Hopfen.",
    "pub_beer_070": "Starkes, rötlich-braunes Bier mit Noten von Malz, Rosinen und Toffee. Im Eichenfass gereift mit weichem, süßem Abgang.",
    "pub_beer_071": "Goldenes Bier, leicht trüb. Helles Zitrus- und Birnenaroma mit süßer Banane, Nelke und Koriandernoten. Seidig-weich mit subtiler Bitterkeit und heller Kohlensäure für einen langen, weichen Abgang.",
    "pub_beer_072": "Traditionelle Lambic-Mischung, trüb und golden. Helle Zitrusnoten von Grapefruit und grünem Apfel, ergänzt durch dezente Eichen- und Weißwein-Anklänge. Herber Geschmack mit Zitronengras, Aprikose, Vanille und Nüssen. Knackig und trocken mit lebendiger Kohlensäure.",
    "pub_beer_073": "Drei Jahre in Eichenfässern gereifte Lambic-Biere. Aroma von neuem Leder, Zitrone und leichter Pistazie. Spritzig und trocken mit heller Säure und tanninhaltigem, würzigem Abgang.",
    "pub_beer_074": "Malzige Karamellnuancen harmonieren mit einem angenehmen, bitteren Akzent von 31 IBU. Gerstenmalz, Hopfen und Kandiszucker für Genussmomente in der Weihnachtszeit.",
    "pub_beer_075": "Mild und voller Kirschgeschmack mit leichten, würzigen Weihnachtsgewürzen. Fruchtig-süß mit einer schönen Kombination aus Frucht- und Malzsüße, den holzigen Noten der Fassreifung und weihnachtlichen Gewürzen — Zimt, Nelken und Anis.",
    "pub_beer_076": "Leuchtend orange-rötlicher Bernsteinton mit cremefarbenem Schaum. Aromen von leichtem Karamell und würzigen Nuancen, abgerundet durch leichte Frucht- und Getreidenoten.",
    "pub_beer_077": "Holzfassgereiftes Golden Ale, klares Bernstein. Reichhaltige Noten von Vanille, Toffee und dezenten Eichen- und Whisky-Anklängen. Weicher, ausgewogener, keksiger Malzgeschmack mit Vanille, Toffee und Eiche. Sanfter Charakter mit anhaltendem, süßem Abgang.",
    "pub_beer_078": "Dunkelbraunes Trappistenbier mit fruchtigem Aroma, warmen Vanilletönen, Karamell und gerösteter Schokolade. Voller, malziger, karamell-süßer Geschmack mit dem subtilen, süßen Einfluss von Datteln, Honig und Trockenfrüchten. Der Nachgeschmack ist süß und leicht bitter.",
    "pub_beer_079": "Imperial Stout, bei Zimmertemperatur serviert. Dunkelbraun mit komplexem Aroma aus verbrannter Schokolade, Brandy, Umami und Vanille. Reichhaltig und wärmend mit Leder, Schokolade, Lakritz und Röstmalz. Trockener Abgang mit anhaltendem, bittersüßem Nachgeschmack.",
    "pub_beer_080": "Tief bernsteinfarbenes Trappistenbier. Reichhaltiger Duft von dunklen Früchten, ergänzt durch Karamell, Vanille und dezente nussige Untertöne. Wärmend und weich mit leichten Hefenoten und süßen Noten von Datteln und Karamell, ausgewogen durch Hopfenbitterkeit. Samtige Textur mit lang anhaltendem Abgang.",
    "pub_beer_081": "Der lebendige Mix aus der Nachbarschaft mit Astra, Cola und Orange. Mit Alkohol.",
    "pub_beer_082": "Frisches, hopfiges Quadrupel, das ein ganzes Bouquet von fruchtigen Aromen und malzigem Karamell bietet. 10% Vol.",
    "pub_beer_083": "Belgische Trappisten-Spezialität. Abgerundeter Antrunk mit seidiger Malzmischung und trockenem Mundgefühl mit Noten von Honigkuchen, Feigenkompott und Kakaopulver. Erfrischend bitterer Abgang von Heu, Gras und gerösteten Maronen.",

    # ── BEERS: Fruit Beer (pages 14-16) ──
    "pub_beer_084": "Tief dunkelrotes Fruchtbier. Sanftes, fruchtiges Aroma mit Mandelanklängen und mild-sauren Kirschen. Süßer und fruchtiger Geschmack, weich und samtig.",
    "pub_beer_085": "Trüb-goldenes Lambic-Bier mit starkem Apfelduft, dezenten buttrigen Malz- und Karamellnoten. Ausgewogener Geschmack von grünen Äpfeln, ergänzt durch eine saure Süße. Weich und knackig mit erfrischendem Abgang.",
    "pub_beer_086": "Tief violett-rotes Lambic-Bier. Dominierender Johannisbeer-Duft mit dezenten Eichen- und Hefenoten. Süße Johannisbeer-Aromen, ergänzt durch leichte Säure und einen trockenen, holzigen Abgang.",
    "pub_beer_087": "Tiefrotes Lambic-Bier mit starkem Kirschduft sowie dezenten Eichen- und Hefenoten. Leichte Säure mit trockenem, holzigem Abgang.",
    "pub_beer_088": "Belgisches Fruchtbier mit Fairtrade-Banane. Reifer Bananenduft und süßer, fruchtiger Geschmack mit dezentem Bier-Nachgeschmack. Glutenfrei.",
    "pub_beer_089": "Belgisches Fruchtbier mit Fairtrade-Mango. Frischer Mango-Duft und süßer, fruchtiger Geschmack mit dezentem Bier-Nachgeschmack. Glutenfrei.",
    "pub_beer_090": "Belgisches Fruchtbier mit Fairtrade-Kokosnuss. Exotischer Kokos-Duft und süßer, fruchtiger Geschmack mit dezentem Bier-Nachgeschmack. Glutenfrei.",
    "pub_beer_091": "Süß-saures, kirschdominiertes Fruchtbier. Die beste Art, sich an warmen Sommertagen zu erfrischen.",
    "pub_beer_092": "Fruchtig, süß und erfrischend herb. Obergärig mit speziellen Bakterien und Kirschen gebraut, gefolgt von einer zweiten Gärung. 18 Monate im Keller gereift.",
    "pub_beer_093": "Traditionelles belgisches Lambic-Fruchtbier, tief rubinrot. Intensives Sauerkirsch-Aroma mit Mandelanklängen und dezenter Eiche. Mittlerer Körper, mäßige Kohlensäure und leicht trockener Abgang.",
    "pub_beer_094": "Flämisches rotbraunes Ale, zwei Jahre in Eichenfässern gereift. Ausgewogener, süß-saurer Kirschgeschmack mit Untertönen von roten Johannisbeeren, Erdbeeren und einem Hauch von Eiche.",
    "pub_beer_095": "In Yorkshire gebrautes Fruchtbier. Markante Noten von Süßkirschen vereint mit dezenten Malz- und Hefeanklängen. Bio.",
    "pub_beer_096": "Tief rötlich-braunes, belgisches Fruchtbier. Ausgewogener, leicht süßer und sanft bitterer Kirschgeschmack mit Aromen von Holz, Mandel und Kirschen sowie einer Hefenote.",
    "pub_beer_097": "Kombiniert La Chouffe mit Sauerkirschen. Anklänge von Erdbeere, Mandel, Gewürzen und süßem Portwein. Vollmundig, süß und lebendig mit einer bitteren Note.",
    "pub_beer_098": "Delirium Red Strong Fruit Beer mit einer großzügigen Portion Kirsche. Der fruchtige Kirschgeschmack steht im Mittelpunkt.",
    "pub_beer_099": "Klares, hellgoldenes, glutenfreies Lager. Dezente Malzsüße mit einem Hauch von Gras und Zitrone. Mäßig bitter mit süßem, trockenem Abgang.",
    "pub_beer_100": "Tiefbraunes, fast schwarzes, glutenfreies Stout. Sanftes Röstmalz- und Kaffee-Aroma mit dezenter Schokoladensüße und milder Bitterkeit. Mittlerer Körper mit samtigem, leicht cremigem Abgang.",
    "pub_beer_101": "Goldenes, klares, niederländisches, glutenfreies IPA. Intensiver, tropischer Fruchtgeschmack mit Zitrus- und Kiefernnoten sowie ausgeprägter Bitterkeit.",

    # ── BEERS: IPA Bottles (page 17) ──
    "pub_beer_102": "Knackiges, hellgoldenes, belgisches IPA. Intensives Zitrus-Aroma von Grapefruit und Limette mit hefiger Würze. Seidig-weich und tropisch mit Zitrusnoten, die sanfte Bitterkeit hält es erfrischend.",
    "pub_beer_103": "Helles, kupferfarbenes, englisches IPA. Erdiges und blumiges Aroma mit ausgewogener Toffee- und Kekssüße, durchschnitten von harziger, kräuteriger Hopfenbitterkeit und Anklängen von Orangenschalen-Würze.",
    "pub_beer_104": "Intensives, zitrusartiges, tiefgoldenes Double IPA. Kräftiger, hopfenbitterer Geschmack, geschichtet mit Orange und Ananas sowie Kiefernharz und solidem Karamellmalz. Vollmundig und weich mit warmem Abgang und hopfiger Trockenheit.",
    "pub_beer_105": "Hopfiges Double IPA, tief bernsteinfarben-gold. Tropisches Mango-, Maracuja- und Zitrus-Aroma mit einem Hauch von Kiefer und Harz. Vollmundig und weich mit cremiger, hopfiger Bitterkeit.",
    "pub_beer_106": "Helles, tropisches IPA, spritzig beim ersten Schluck mit Kiefernharz und sanfter Bitterkeit, die die Maracuja- und Guaven-Fruchtigkeit ausgleicht. Weiche Kohlensäure und sauberer, trockener Abgang.",
    "pub_beer_107": "Grapefruit- und Ananas-Noten dominieren, begleitet von Mango- und Pfirsich-Aromen. Die Kveik-Hefe macht es prickelnd und besonders erfrischend, wenn es gekühlt genossen wird.",

    # ── BEERS: Lager Bottles (page 18) ──
    "pub_beer_108": "Helles, mexikanisches Lager, strohgelb. Leichte Malzsüße mit dezenten Getreidenoten. Knackig und sauber, leicht süß mit sanfter Hopfenbitterkeit. Leichter Körper, süffig.",
    "pub_beer_109": "Das weltweit erste Tequila-aromatisierte Bier. Helles, goldfarbenes Lager mit süßem Malz- und dezentem Zitrus-Aroma sowie einer markanten Tequila-Note. Knackig und erfrischend.",
    "pub_beer_110": "Helles Lager, gebraut in Hamburg. Hell und klar, blasses Stroh. Leichtes, ausgewogenes Malz-Aroma mit einem Hauch Bitterkeit. Leichter Körper, sehr süffig.",
    "pub_beer_111": "Niederländisches, trüb-goldenes IPA. Saftiges, tropisches Fruchtaroma von Mango und Maracuja, geschichtet mit weicher, kräuteriger Hopfigkeit. Mittlerer Körper, weich und süffig.",
    "pub_beer_112": "Ursprünglich als Halloween-Saisonbier gebraut, dieses englische Pale Ale ist bernsteinfarben mit Zitrus- und tropischem Fruchtaroma, ausgewogen mit leichtem, keksigem Malz. Heller Zitrus- und tropischer Geschmack mit sauberer, moderater Bitterkeit.",

    # ── BEERS: Pils & Stout (page 19) ──
    "pub_beer_113": "Traditionelles Pilsner aus den Niederlanden. Helles, goldfarbenes Klares mit leichtem, malzig-süßem Aroma und blumig-hopfigem Geschmack. Knackig und sauber, süffig.",
    "pub_beer_114": "Schottisches Stout, das vor Röstkaffee- und Schokoladengeschmack nur so strotzt, mit leicht bitterem Abgang. Tiefschwarze Erscheinung und samtige Textur mit geröstetem Malz- und Schokoladen-Aroma und einer dezenten Rauchnote.",
    "pub_beer_115": "In Yorkshire gebrautes, tiefbraunes Stout mit reichhaltigem Röstmalz- und dunklem Schokoladen-Aroma mit sanfter Süße und dezentem Kaffee-Geschmack. Mittlerer Körper und samtig, sehr genussvoll.",
    "pub_beer_116": "Tiefschwarzes Stout, bei Zimmertemperatur serviert. Reichhaltiges Röstmalz- und dunkles Schokoladen-Aroma mit Espresso-Noten. Vollmundig und intensiv mit Schichten von Kaffee, dunkler Schokolade und Karamell. Schwerer, samtiger Abgang.",
    "pub_beer_117": "Trockener Röstmalz-Eindruck mit vollmundigem Mundgefühl. Espresso-Noten und der typische Inselhopfen Fuggles dominieren den Geschmack.",
    "pub_beer_118": "Strotzt vor reichen Röstmalz- und Röstgersten-Aromen. Aromen von Bitterschokolade, Röstkaffee und würzigen dunklen Früchten, ergänzt durch eine komplexe, bittere Mischung von Hopfensorten.",

    # ── BEERS: Weizen (page 20) ──
    "pub_beer_119": "Klassisches, deutsches Weizenbier. Trüb golden-orange mit Aroma von Banane, Nelke und Malzsüße. Sanfter Bananengeschmack, gefolgt von dezenten Zitrusnoten und einem sauberen Abgang. Mittlerer Körper, erfrischend.",
    "pub_beer_120": "Dubbel Witbier, gebraut für die Festzeit. Mehr Malz, mehr Alkohol, mehr Farbe, mehr Geschmack, mehr Genuss. Ein vollmundiges, großes Wit.",

    # ── BEERS: Canned Beer (pages 21-24) ──
    "pub_beer_121": "Traditionelles Ale mit bernstein-kupferfarbener Erscheinung. Leichte Malzsüße und dezentes, keksiges Aroma, ergänzt durch blumigen Hopfen. Milde Karamell-Aromen und sanfte Bitterkeit.",
    "pub_beer_122": "Trüb golden-orangefarbenes New England IPA. Tropisches Frucht- und Zitrus-Aroma mit saftigem Mango- und Ananas-Geschmack, ausgewogen durch milde Malzsüße und weiche Bitterkeit.",
    "pub_beer_123": "Trüb-nebliges Hazy IPA mit hellen, goldenen Farbtönen. Meisterhafte Kombination von Citra-, Mosaic- und Amarillo-Hopfen. Modernes Brauen trifft auf traditionelle Handwerkskunst.",
    "pub_beer_124": "London Fog IPA, gesättigt mit Citra, Mosaic und Idaho 7, das vor Frucht-Bubblegum-Aromen von Mango, Orangenschale, Ananas und reifen Pfirsichen nur so strotzt.",
    "pub_beer_125": "Gebraut mit Peacharine-Hopfen von Freestyle Hops. Intensive Noten von Steinobst, Nektarine, Limettenabrieb und Mandarine.",
    "pub_beer_126": "Hopfiges IPA mit tropischen Mango-Aromen und erfrischenden Zitrusnoten. Dezente, herbe Akzente umrahmen dieses extrem feine IPA. Wunderbar herb und trocken im Abgang.",
    "pub_beer_127": "Das BW-17 ,,BioWar''-Projekt hat eine geringere Bitterkeit, aber ein sehr intensives, fruchtiges Aroma. Extrem erfrischend, weich und saftig. Ausgezeichnet mit der Silbermedaille beim Good Beer Wettbewerb.",
    "pub_beer_128": "Vietnow IPA überrascht mit einer harmonischen Komposition aus tropischen Früchten, Zitrusnoten und einer dezenten, für ein IPA typischen Harzigkeit. Am Gaumen entfaltet sich eine frische Welle tropischer Früchte, gefolgt von einer angenehm ausgewogenen Bitterkeit.",
    "pub_beer_129": "Am Gaumen trifft die intensive Fruchtigkeit auf eine angenehm weiche Textur, unterstützt durch Weizen- und Hafermalz sowie Weizenflocken. Ein samtiges Mundgefühl, das perfekt mit dem hopfigen Charakter harmoniert. Die verwendeten Galaxy- und El Dorado-Hopfensorten sind echte Stars der IPA-Welt: Sie bringen tropische Aromen und eine dezente Harzigkeit, ohne zu bitter zu sein.",
    "pub_beer_130": "Starke Bitterkeit und typische Westküsten-Aromen — eine Mischung aus Kiefernnadeln und tropischen Früchten, die dem Bier eine erfrischende Frische verleihen. Ein Bier für Liebhaber von Hopfenbitterkeit und für alle, die den rustikalen, aber modernen Charakter eines West Coast IPA schätzen.",
    "pub_beer_131": "Der beliebte Klassiker jetzt in glutenfreier Version. Leicht golden mit dezenter Trübung und kräftigem Getreidemalz-Aroma mit tropischen Fruchtaromen. Ausgewogen durch Karamellsüße und endend mit knackiger Bitterkeit.",
    "pub_beer_132": "Glutenfreies IPA, klares, helles Gold. Intensives Zitrus- und tropisches Fruchtaroma mit Grapefruit, Maracuja und Mango. Milde Bitterkeit mit sauberem, trockenem Abgang.",
    "pub_beer_133": "Hopfige Aromen von Mango und Ananas. Explosiver Geschmack, zarte Zitrus-Highlights und erfrischend ausgewogene Bitterkeit. Kissenweiches Mundgefühl mit einer schönen, leichten Trübung.",
    "pub_beer_134": "Erfrischendes Sauerbier, leicht trüb. Leicht herbes Aroma mit Anklängen von grünem Apfel, Zitrone und Weizenmalz. Knackig und erfrischend mit hellen Zitrus- und Sauernoten, ausgewogen durch weiche Malzsüße.",
    "pub_beer_135": "Kräftig, herb und saftig zugleich — dieses vegane, moderne Sauerbier strotzt vor intensiven Fruchtaromen und Geschmack, alles auf einem zarten, sauren Abgang unserer hauseigenen Mischkultur.",
    "pub_beer_136": "Wässrig machende Aromen von traditionellen Erdbeeren mit Sahne, verfeinert durch die Zugabe von Laktose und weicher Vanille.",
    "pub_beer_137": "Herb und erfrischend — diese trübe Limonade strotzt vor Zitrusaromen aus frischem Zitronensaft und -abrieb. Gepaart mit dem prickelnden Charakter unserer Mischkultur-Basis ist es ein veganes, leichtes und trinkbares Session Sour, abgerundet durch anhaltende Süße.",
    "pub_beer_138": "Tief trüb-golden mit großer weißer Schaumkrone. Mango, flauschige Wolken und Ananas kommen in Nase und Geschmack durch, akzentuiert durch eine weiche Textur und sehr dezente Trockenheit.",
    "pub_beer_139": "Tropische Aromen von Ananas, Zitrus und einem Hauch von Kokosnuss erwarten Sie in Nase und Gaumen — eine Kombination der verwendeten Citra-, Mosaic- und Sabro-Hopfensorten. Das Zusammenspiel von Weizenmalz, Hafermalz und Weizenflocken sorgt für eine angenehm weiche Textur und ein rundes Trinkerlebnis.",
    "pub_beer_140": "Beim ersten Schluck erleben Sie die tropische Frische von Ananas, eingehüllt in eine dezente Süße, während Limette und Litschi für eine angenehm fruchtige Säure sorgen. Die HBC-1019-Hopfen tragen mit ihrer leichten Würze perfekt zu diesem fruchtigen Bouquet bei. Haferflocken und Weizenmalz sorgen für vollmundige Textur und saftiges Mundgefühl.",
    "pub_beer_141": "Der Geschmack von frischer Mandarine und saftiger Maracuja ist sofort erkennbar und wird von einer weichen, fast cremigen Textur getragen. Die Hopfen bringen komplexe tropische Noten von Mango und Zitrus sowie einen Hauch von Harzigkeit, erzeugt durch die Kombination von Columbus-, Chinook- und Kohia-Nelson-Hopfen. Riwaka, Peacharine und Mosaic sorgen für eine besonders fruchtige Note.",
    "pub_beer_142": "Reiche Hopfennoten von Zitronengras, Grapefruit und Kiefer sorgen für die entsprechende Geschmackskraft. Alkoholfrei.",

    # ── Tankbuster Cans ──
    "pub_beer_143": "DDH Dual Hop NEIPA mit Superdelic- und Alora-Hopfen. Ein doppelt trockengehopftes New England IPA mit berstendem Hopfencharakter.",
    "pub_beer_144": "Eine Hommage an die 80er und 90er. Session-Version des New England DDH mit einer Mischung aus Citra- und Cascade-Hopfen. Nostalgisches IPA — in drei Worten: ,,Bitter-Weich-Tropisch''.",
    "pub_beer_145": "Ein wirklich erfrischendes West Coast IPA mit unverkennbarer Kräuterigkeit in Aroma und Geschmack. Gehopft mit Citra-, Nectaron- und Harlequin-UK-Sorten. Ein Kollaborationssud mit Abbeydale UK.",
    "pub_beer_146": "Mandarinen-Hafer-IPA. Gebraut mit Azacca BBC, Citra Cryo und Hallertauer Blanc sowie echtem Mandarinensaft. Ein fruchtiges IPA mit hellem Zitrus-Punch und weichem Haferkörper.",
    "pub_beer_147": "NZ NEIPA, gebraut mit Citra-, Rakau-, Mosaic-, Wa-iti-, Kohatu- und Azacca-Hopfen. Geburtstags-Sud mit IBU Craft Beers aus Gliwice. Tropisch und saftig.",
    "pub_beer_148": "Ausgeprägtes, hopfiges West Coast IPA mit intensiver Bitterkeit. Ausgewogene Zitrus-, Kiefern- und Harznoten verschmelzen perfekt mit dem markanten Aroma von Grapefruit und tropischen Früchten. Helle, goldene Farbe und saubere Textur unterstreichen den klassischen amerikanischen Stil.",
    "pub_beer_149": "Obergäriges IPA, das klassische IPA-Merkmale mit einem einzigartigen kanadischen Twist kombiniert. Der Geschmack wird von fruchtigen Noten dominiert — Mandarine, Ananas und Pfirsich — die perfekt mit einer deutlichen, aber angenehmen Bitterkeit harmonieren.",
    "pub_beer_150": "Ein IPA, das drei Formen des Citra-Hopfens präsentiert: Citra Lupomax, Citra BBC und Citra Spectrum. Eine intensive Feier des Citra-Hopfens.",
    "pub_beer_151": "DDH Japanese IPA, das moderne Brautechniken mit japanischer Präzision kombiniert. Doppelt trockengehopft für ein reiches Aroma von Zitrus, Ananas und dezenten, blumigen Noten. Helles Gold mit intensiver, aber ausgewogener Bitterkeit, die perfekt mit der fruchtigen Süße harmoniert. Ein IPA, das kräftigen, modernen Charakter mit Finesse und Subtilität verbindet.",
    "pub_beer_152": "Ein ausgeprägtes IPA mit hopfigem Aroma und Geschmack, aber ohne Alkohol. Trockengehopft mit einer Komposition von gleich vier Hopfensorten: Citra, Amarillo, Chinook und Lubelski. Die Zugabe von Sencha-Earl-Grey-Tee vervollständigt das Zitrus- und Harzprofil.",

    # ── Ciders ──
    "pub_beer_153": "Irlands beliebtester Cidre. Klar und golden mit frischem Apfel und milden, blumigen Noten, ausgewogen durch eine sanfte Säure mit sauberem, erfrischendem Abgang.",
    "pub_beer_154": "Rubinroter Cidre mit frischem, rotem Beerenaroma und Geschmacksnoten von Erdbeere, Himbeere und Apfel. Dezente Süße mit herbem Abgang.",
    "pub_beer_155": "Hellgoldener Cidre mit frischem Birnenaroma und süßen Birnen- und Apfelnoten, ausgewogen durch eine süße Säure und weichen Abgang.",
    "pub_beer_156": "Dessert-artiger Cidre mit reichhaltigem, süßem Toffee- und Karamell-Geschmack und Apfelanklängen.",
    "pub_beer_157": "Süßer Cidre mit frischem Himbeergeschmack, ausgewogen durch einen Hauch von spritziger Limette und knackigen Apfel-Untertönen.",
    "pub_beer_158": "Süßer Cidre mit frischem Apfel- und Birnengeschmack und erfrischendem Abgang.",
    "pub_beer_159": "Tief rubinrot gefärbter, süßer Cidre, der nach reifen Himbeeren und Brombeeren schmeckt.",
    "pub_beer_160": "Süßer Cidre mit frischem Zitrus-Orangen-Geschmack und einem Schuss spritziger Zitrone.",
    "pub_beer_161": "Vollmundiger, bernsteinfarbener Cidre mit süßem, rotem Beerenaroma von Erdbeere, geschichtet mit knackigem Apfel.",
    "pub_beer_162": "Leuchtend goldener, knackiger Apfel-Cidre mit dezenten Honig- und Blumennoten und ausgewogener Süße mit sauberem, herbem Abgang.",
    "pub_beer_163": "Trüber, bernstein-orangefarbener, saftiger Apfel-Birnen-Cidre, weich und fruchtig mit sanfter Herbheit.",
    "pub_beer_164": "Blassrosa prickelnder Cidre mit süßen, roten Beeren- und Apfelnoten, weichem Abgang und leichter Perlage.",
    "pub_beer_165": "Leuchtend orangefarbener Cidre mit spritzigem Blutorangen-Geschmack und einem Hauch von Apfelsüße.",
    "pub_beer_166": "Reichhaltiger, erfrischend fruchtiger Cidre aus den süßesten Tafeläpfeln, mit frischem Beerenaroma und kräftigem, natürlichem Johannisbeer-Geschmack — reichhaltige und fruchtige Perfektion.",
    "pub_beer_167": "Starker, rustikaler Cidre mit tiefer, goldener Farbe und kräftigem Apfelcharakter mit dezentem, fruchtigem Unterton.",
    "pub_beer_168": "Eine süße Mischung aus Äpfeln und Cola, die einen unverwechselbaren, ausgewogenen, süßen Geschmack mit einer spritzig-sauren Note erzeugt.",
    "pub_beer_169": "Tropische Maracuja und Anklänge von Zitrus und Apfel sind die Hauptaromen dieses leicht trüben Cidres.",
    "pub_beer_170": "Rosafarbener und leicht prickelnder Cidre mit süßen Himbeeraromen, ausgewogen durch eine spritzige Zitrone.",
    "pub_beer_171": "Hergestellt aus 88% Birne und 12% Apfel. Süß im Geschmack mit einem köstlichen, fast exotischen Aroma.",
    "pub_beer_172": "Erfrischender Apfel-Cidre, verfeinert mit Rhabarbersaft, mit knackigem, sauberem Abgang.",
    "pub_beer_173": "Erfrischender Apfel-Cidre, verfeinert mit Rhabarber- und Mango-Saft, mit einer süßen, tropischen Note.",
    "pub_beer_174": "Hergestellt aus selbst angebauten, frisch gepressten Cidre-Äpfeln. Diese alkoholarme Option hat einen süßen, aber frischen Geschmack.",
    "pub_beer_175": "Erfrischender Apfel-Cidre, verfeinert mit tropischem Mango-Saft und spritzigen Limetten-Twists.",
    "pub_beer_176": "Diese tropische Mischung aus Orangen- und Ananassäften verfeinert einen frischen Apfel-Cidre für einen exotischen, aber erfrischenden Abgang.",
    "pub_beer_177": "Erfrischender Apfel-Cidre, verfeinert mit hellen, zerdrückten Himbeeren, mit einer süßen, tropischen Note.",
    "pub_beer_178": "Cocktail-inspirierter Cidre, der die Aromen von saftigen Erdbeeren, Limetten und einer dezenten Rum-Note kombiniert.",
    "pub_beer_179": "Cocktail-inspirierter Cidre, der die Aromen von Cranberries und einem Spritzer Limette kombiniert.",
    "pub_beer_180": "Cocktail-inspirierter Cidre, der die Aromen von Maracuja und Vanille kombiniert.",
    "pub_beer_181": "Cocktail-inspirierter Cidre, der die Aromen von saftiger Mango und Kiefer mit einem Rum-Twist kombiniert.",
    "pub_beer_182": "Fruchtiger Cidre, süß und frisch mit einer Mischung aus Erdbeeren und spritzigen Limetten. Leicht prickelnd und ein weiches Trinkerlebnis.",
    "pub_beer_183": "Fruchtiger Cidre, süß und frisch mit einer Mischung aus Waldbeeren. Leicht prickelnd und ein weiches Trinkerlebnis.",
    "pub_beer_184": "Alkoholarmer Cidre, süß und leicht säuerlich mit anhaltendem Apfel-Nachgeschmack.",
    "pub_beer_185": "Diese Mischung aus roten Beeren und Apfel ist süßer und hinterlässt einen sauberen, anhaltenden, fruchtigen Abgang.",
    "pub_beer_186": "Prickelnder Cidre mit dem Geschmack bittersüßer Orangen: eine erfrischende Kombination aus angenehmer Bitterkeit und fruchtiger Süße. Intensives, fruchtiges Orangenaroma und leichte Kräuternoten. Angenehm bitter mit anhaltender Süße und Säure.",
    "pub_beer_187": "Erfrischend fruchtiger Cidre mit dem Geschmack von saftig-süßer Mango und prickelnder, leicht herber Limette. Intensive Mango-Aromen mit einem Hauch von Limette. Ausgewogen zwischen süßen und herben Noten. Lang anhaltender und erfrischender Geschmack.",
    "pub_beer_188": "Erfrischender Cidre trifft auf den intensiven Geschmack von Brombeeren. Die Mischung aus milder Süße und leicht herben Noten erzeugt eine wahre Geschmacksexplosion. Lang anhaltender Brombeergeschmack mit angenehmer Säure und anhaltender Süße.",
    "pub_beer_189": "Leichter, spritziger Cidre mit hellgoldener Farbe und einem Hauch von Rosa. Schmeckt nach frischen grünen Äpfeln mit heller Himbeersüße — ausgewogen und erfrischend.",
    "pub_beer_190": "Trockener Eichenfass-Craft-Cidre, hergestellt aus einer Mischung der feinsten Herefordshire-Cidre-Äpfel, gelagert und gereift in abgelagerten Eichenfässern, die den knackigen Geschmack des Holzes und der Frucht vereinen.",
    "pub_beer_191": "Spritziger Bio-Apfel trifft auf süße Waldbeeren. Fruchtiger, trockener Abgang mit Noten von Brombeere und Kirsche.",
    "pub_beer_192": "Vollgepackt mit Brombeere, Himbeere und Heidelbeere auf einer spritzigen Tafelapfel-Basis. Dieser super-fruchtige Cidre wird mit Weinhefe vergoren, um die süße Beerenfront delikat auszubalancieren. Tief, üppig und tottrinkbar.",
    "pub_beer_193": "Halbtrockener Cidre mit brillanter Strohfarbe, leichtem Körper, reinem Apfelgeschmack und einem sanften Apfelblüten-Abgang. Hergestellt in einer kleinen, unabhängigen britischen Brauerei, der ältesten in Yorkshire. Bio und glutenfrei.",

    # ── Clearance Beers ──
    "pub_beer_194": "Trübes, honiggelbes, alkoholfreies Pale Ale mit fruchtigem Pfirsich-, Zitrus- und Aprikosen-Aroma. Leicht keksig und malzig, ausgewogen mit blumig-fruchtigen Hopfen und Noten von Maracuja, Mango und Grapefruit. Abverkaufsware.",
    "pub_beer_195": "Alkoholfreies IPA mit vollen Hopfenaromen von Grapefruit und Limette, leuchtend orange im Glas und knackiger Bitterkeit — ohne Kompromisse beim Geschmack. Abverkaufsware.",
    "pub_beer_196": "Gebraut mit Pale-Ale-, Roggen-Kristall- und Cara-Malz. Citra und eine Mischung anderer amerikanischer Hopfensorten erzeugen großartige Zitrusaromen. Abverkaufsware.",
    "pub_beer_197": "Der großartige Geschmack von La Chouffe — fruchtiges Bouquet, ein Hauch von Würze, unschlagbare Frische — nur ohne Alkohol. Abverkaufsware.",
    "pub_beer_198": "Prickelndes Bier mit orange-rosa Farbton, serviert On the Rocks. Fruchtige Aromen von Pfirsich, Mango, Aprikose und Limette. Ein einzigartiges und erfrischendes Servierritual. Abverkaufsware.",
    "pub_beer_199": "Englisches Bitter mit klarem, bernsteinfarbenem Ton und orangefarbenen Reflexen. Reichhaltiges, malziges Aroma mit Karamell- und sanften Röstnoten. Malzig und ausgewogen durch zurückhaltende Bitterkeit. Abverkaufsware.",
    "pub_beer_200": "Schwedisches Session IPA, orange-gelb mit exotischem, fruchtigem Aroma. Vollmundig mit ausgewogenem, fruchtig-hopfigem Geschmack und Bitterkeitsanklängen. Abverkaufsware.",
    "pub_beer_201": "Reiche Fruchtigkeit, gefolgt von kräftiger, aber gut integrierter Bitterkeit. Die amerikanischen Hopfensorten schaffen eine schöne Balance zwischen tropischer Süße und harziger Trockenheit. Abverkaufsware.",
    "pub_beer_202": "Saftiges IPA mit Mango-Geschmack und einem Hauch von Kiefernharz, ausgewogen durch moderate Bitterkeit und weichen, erfrischenden Abgang. Abverkaufsware.",
    "pub_beer_203": "In Kollaboration mit Monkish gebraut. Weicher, hopfiger Geschmack mit einem Hauch von süßer Mango und einer trüben, tiefgoldenen Farbe. Abverkaufsware.",
    "pub_beer_204": "Vollmundiges Brown Ale mit Aromen von Walnüssen und Röstgerste und einem angenehm trockenen Abgang. Abverkaufsware.",
    "pub_beer_205": "Tiefrote, fast bräunliche Farbe mit markanter, cremiger Schaumkrone. Süße Malznoten von Karamell und Hopfenaromen dunkler Früchte. Kräftig und kompromisslos. Abverkaufsware.",
    "pub_beer_206": "Vollmundiges, trübes IPA, inspiriert von Lagerfeuer-Sessions. Tropische Fruchtaromen und ein Hauch von Kokosnuss. Am besten mit Freunden zu genießen. Abverkaufsware.",
    "pub_beer_207": "Naturtrübes Radler. Angenehm spritzig-sauer mit fruchtig-frischem Aroma reifer Zitrusfrüchte — Zitronen, Limetten und Orangen. Ein leichter Hopfenanklang am Ende. Abverkaufsware.",
    "pub_beer_208": "Dunkles, obergäriges Starkbier mit Flaschengärung. Aromen von roten Früchten und getoastetem Brot mit Noten von Schokolade und Toffee. Abverkaufsware.",
    "pub_beer_209": "Frisches Lager, gebraut und verfeinert mit Golding-Hafer. Rund, spritzig-sauer und erfrischend, aber niemals langweilig. Abverkaufsware.",
    "pub_beer_210": "Klares, goldenes Helles Lager mit sauberem und ausgewogenem Geschmack. Leicht süßes Malz und dezente Hopfenbitterkeit. Weiches Aroma mit sanften, blumigen Hopfen und Brotigkeit. Abverkaufsware.",
    "pub_beer_211": "Gebraut mit drei Spezialmalzen für ein angenehm weiches Bier mit intensiven Röstnoten, die an Kaffee und dunkle Schokolade erinnern. Abverkaufsware.",
    "pub_beer_212": "Fruchtige Aromen von Zitronenschale, Papaya und Guave mit mittlerer Hopfenbitterkeit und goldener, leicht trüber Farbe. Abverkaufsware.",
    "pub_beer_213": "Grapefruit-Overkill. Intensive US-Aromahopfen mit Orangen- und Kiefernnoten auf einer Karamellmalz-Basis. Spritzig-sauer, kräftig und zitrusbetont. Abverkaufsware.",
    "pub_beer_214": "Erfrischende Zitrusnoten, gefolgt von tropischen Früchten und blumigen Noten, die den stabilen Malzkörper perfekt ergänzen. Balanciert gekonnt Hopfen und Malz. Abverkaufsware.",
    "pub_beer_215": "Helles, goldfarbenes mexikanisches Lager mit leichtem Mais-Aroma und Malzsüße. Erfrischender, heller Limetten-Geschmack und ein Hauch von Salzigkeit. Abverkaufsware.",
    "pub_beer_216": "Saftiges Double New England IPA mit Riwaka-, Motueka-, Citra- und Elani-Hopfen. Intensive Noten tropischer Früchte — Maracuja und Mango — mit deutlichen Zitrus- und Limetten-Akzenten. Abverkaufsware.",
    "pub_beer_217": "Fruchtiges, erfrischendes und hopfiges DDH Canadian IPA mit Aromen von Birne, Trauben und Wassermelone. Abverkaufsware.",
    "pub_beer_218": "Aromen von Kumquat, Maracuja, Mango und weißen Früchten explodieren förmlich im Glas. Riwaka- und Elani-Hopfen sorgen für harmonische, fruchtige Balance mit klarem, kraftvollem Charakter. Abverkaufsware.",
    "pub_beer_219": "Angenehme, milde Bitterkeit, perfekt ergänzt durch tropische und Limetten-Aromen von Citra BBC-, Motueka- und Cascade BBC-Hopfen. Abverkaufsware.",
    "pub_beer_220": "Modernes Frucht-Gose mit kühlem, kräuterigem Gurken-Aroma, gepaart mit der spritzigen Zitrusfrische von Limette. Die Birne fügt eine weiche, saftige Komponente hinzu. Abverkaufsware.",
    "pub_beer_221": "Intensives Triple IPA mit saftigen Hopfennoten und cremiger Textur — perfekt für kühle Abende. Abverkaufsware.",
    "pub_beer_222": "Erfrischendes NEIPA mit intensiven Limetten- und Litschi-Aromen. Saftig, fruchtig und weich — das perfekte Sommerbier. Abverkaufsware.",
    "pub_beer_223": "Double IPA nach New-England-Art, dick und cremig, dominiert von tropischen Aromen aus Mango und kandierter Ananas, eine leichte Süße, ausgewogen durch einen langen, weichen, bitteren Abgang. Abverkaufsware.",
    "pub_beer_224": "Tropische Zitrusnoten treffen auf Karamell von den verwendeten Pale- und Karamellmalzen. Dazu kommen dezente, fast würzige Akzente. Trocken, fein prickelnd und kraftvoll. Abverkaufsware.",
    "pub_beer_225": "Strohgelbes mexikanisches Blonde Ale. Knackiges und sauberes Aroma mit einem Hauch von Limettenschale. Leichte Malzsüße, ausgewogen durch milde Hopfenbitterkeit mit erfrischendem Zitrus-Limetten-Twist. Abverkaufsware.",
    "pub_beer_226": "Helles und klares, goldenes Ale. Sanftes, blumiges Hopfenaroma mit Anklängen von Zitrus und honigartigem Malz. Ausgewogene Süße von hellem Malz, dezente Zitrusfruchtigkeit und milde Hopfenbitterkeit. Sauber, knackig und süffig. Abverkaufsware.",
    "pub_beer_227": "Süffiges Pale Ale, das zeitgenössische Weichheit nahtlos mit bewährter Trinkbarkeit verbindet. Weicher Körper und trockener Abgang, der die saftigen Aromen am Gaumen nachklingen lässt. Der Inbegriff von Sessionability. Abverkaufsware.",
    "pub_beer_228": "Deutsches Pils, gebraut mit aromatischen Hopfen. Unkompliziert, klassisch hopfig. Abverkaufsware.",
    "pub_beer_229": "Zöliakie- und vegan-freundliches West Coast IPA. Zitrus- und Kiefernaroma mit einem Hauch von Pfirsich. Ein Hauch von Süße durch leichtes Karamellmalz. Abverkaufsware.",

    # ── GINS ──
    "pub_gin_001": "Eine Londoner Brennerei, neun Brennanlagen und ebenso viele Botanicals ergeben den meistausgezeichneten Gin der Welt unter der Aufsicht des weltweit erfahrensten Master Distillers. Ein klassischer London Dry Gin mit großem Wacholdercharakter und kräftigen Zitrusnoten — ein authentischer London Dry für alle, die den echten Geschmack von Gin lieben.",
    "pub_gin_002": "Unser weltberühmter Gin in seiner markanten blauen Flasche. Jeder Tropfen enthält zehn handverlesene Botanicals von exotischen Orten der Welt. Wir kochen sie nicht, sondern infundieren sie schonend mit Dampf, um ihre hellen, lebendigen Aromen einzufangen.",
    "pub_gin_003": "Dieser Gin besteht aus Wacholder, Koriander, Engelwurz, Zitronen- und Orangenschale. Er wird dann mit Erdbeer- und Himbeeraromen und einem Hauch Zucker verfeinert, was dem Bosford Rose eine leichte Süße verleiht, um den manchmal bitteren Geschmack von Gin zu mildern.",
    "pub_gin_004": "Wir würden unseren klassischen Caorunn Gin gerne beschreiben, wissen aber nicht, wo wir anfangen sollen. Wir könnten sagen, er hat einen leicht würzigen, vollmundigen und belebenden Geschmack mit sauberem, knackigem Abgang. Oder vielleicht erklärt er sich am besten als moderner London Dry Gin, veredelt mit klassischer keltischer Seele in Form unserer fünf lokal wildgesammelten Botanicals.",
    "pub_gin_005": "Dieser City of London No. 1 London Dry Gin ist ein klassischer, perfekt ausgewogener Gin aus dem Herzen Londons. Neben Wacholder verwendet die Brennerei Engelwurz, Lakritz und Koriandersamen als Botanicals. Für den letzten Schliff werden frische Orangen, Zitronen und rosa Grapefruit verwendet, die dem Gin eine unverwechselbar pikante, fruchtige Note verleihen.",
    "pub_gin_006": "Diese Edition ist ein einzigartiger, würziger Gin-Stil dank der immensen Geschmackspalette. Zu den ursprünglichen fünf Copperhead-Botanicals kommen nicht weniger als 13 sorgfältig ausgewählte Gewürze, die traditionell zum Einlegen verwendet werden. Diese Zutaten — darunter Muskatblüte, Pfeffer, Kassia, Lorbeerblatt, Ingwer, Piment, Fenchel und Dillsamen — werden durch einen Hauch von achtjährigem Genever ergänzt, um diesen weichen und komplexen Geschmack abzurunden.",
    "pub_gin_007": "Ein unverkennbarer London Dry, geboren in der alten und magischen Stadt Edinburgh. Der feinste Getreidealkohol wird mit einer originellen Balance von 14 Botanicals vereint. Dieser preisgekrönte Gin ist eine Liebesarbeit und das Herzstück unseres Sortiments.",
    "pub_gin_008": "Schmeckt wie eine kühle, frische Brise über windgepeitschten, goldenen Sand. Dieser Ausdruck fängt die Wunder der Küste nahe der Stadt ein. Ein sanft süßer, mineralischer Gin aus Botanicals, die an den Stränden rund um Edinburgh gesammelt wurden — er erinnert an einen belebenden Spaziergang an einem schottischen Strand.",
    "pub_gin_009": "Frisch geerntete Muskatquitten, eine seltene Birnenquitten-Sorte, die hinter der Brennerei wächst, sowie ein Aufguss unseres Rausch Kabinetts bilden die Basis für unsere regionale Hommage an den britischen Sloe Gin.",
    "pub_gin_010": "Fifty Pounds Gin ist unser Name, nicht unser Preis! Das Ergebnis ist ein London Dry Gin, der die Jahrhunderte überspannt und es uns erlaubt, Fifty Pounds Gin als historisch im Wesen und modern im Geist zu beschreiben. Von den verwendeten Botanicals bis zur Herstellungs- und Abfüllmethode zollt Fifty Pounds Gin Londons reicher Gin-Geschichte Tribut.",
    "pub_gin_011": "Derselbe preisgekrönte Gin wie in der klassischen grünen Gordon's-Flasche. Nicht lange nachdem wir Anfang des 20. Jahrhunderts mit der Abfüllung begannen, erhielten wir unsere erste große Bestellung von Gordon's, die nach Australien verschickt werden sollte. Zu diesem Anlass entwarfen wir ein neues Exportetikett, das wir noch heute verwenden.",
    "pub_gin_012": "Inspiriert von einem originalen Gordon's-Rezept aus den 1880er Jahren, ist Gordon's Pink perfekt darauf abgestimmt, den erfrischenden Geschmack von Gordon's mit der natürlichen Süße von Himbeeren und Erdbeeren sowie der Säure der Johannisbeere in einem einzigartigen, errötenden Ton zu vereinen. Hergestellt mit ausschließlich natürlichen Fruchtaromen.",
    "pub_gin_013": "Hendrick's ist ein ungewöhnlicher Gin aus elf feinen Botanicals. Die neugierigen und doch wunderbaren Aufgüsse von Rose und Gurke verleihen unserem Geist seinen einzigartig ausgewogenen Geschmack und machen ihn zu einem tadellos weichen, unverwechselbaren Gin.",
    "pub_gin_014": "Zugegeben, es erscheint etwas exzentrisch zu behaupten, dass ein deutsches Gin-Rezept die Kraft hat, große britische Traditionen, die Gewürze Indiens und die reiche Landschaft des Schwarzwalds zu vereinen. Und doch ist es genau diese Exzentrizität, die den rätselhaften und wagemutigen Charakter von Montgomery definiert. Destilliert aus 47 überwiegend ungewöhnlichen, aber regionalen Botanicals wie Preiselbeeren und vermischt mit natürlichem Quellwasser.",
    "pub_gin_015": "OPIHR Spices of the Orient Gin wird aus einer Auswahl exotischer, handverlesener Botanicals handgefertigt, sorgfältig ausgewählt von OPIHRs Master Distiller — darunter würzige Kubebenbeeren aus Indonesien, schwarzer Pfeffer aus Indien und Koriander aus Marokko.",
    "pub_gin_016": "Gin, hergestellt wie früher — und wie wir glauben, dass er sein sollte. 2009 errichteten wir Londons erste Kupferbrennblase seit 189 Jahren und stellten unseren preisgekrönten Gin von Hand in kleinen Chargen her. Unsere Mission war einfach: einen London Dry Gin von wirklich kompromissloser Qualität und Charakter zurück in die Stadt zu bringen, in der Gin seinen Namen erhielt.",
    "pub_gin_017": "Das Glück begünstigt die Mutigen. In den 1830er Jahren scheute Charles Tanqueray nicht davor zurück, seine kühnen Ideen zu mischen. Sein geniales Streben nach Perfektion zahlte sich aus und schuf Tanqueray London Dry, einen perfekt ausgewogenen Gin und einen der meistausgezeichneten Gins der Welt.",
    "pub_gin_018": "Tanqueray Flor de Sevilla Distilled Gin ist ein spritziger, fruchtiger Gin, der einen kräftigen und bittersüßen Geschmack der sonnenverwöhnten Mittelmeerregion bietet. Sevilla-Orangen werden mit Orangenblüte und den vier Botanicals unseres klassischen London Dry Gin destilliert — kieferiger Wacholder, pfeffriger Koriander, aromatische Engelwurz und süßes Lakritz — für einen ausgewogenen, fruchtigen Geschmack.",
    "pub_gin_019": "Das Erbe des originalen London Dry-Rezepts weiterführend, setzt Tanqueray No. 10 den Standard als erster Ultra-Premium-Gin. In kleinen Chargen destilliert mit den vier ursprünglichen Botanicals des London Dry und der Zugabe von frischen, ganzen Grapefruits, Orangen, Limetten und Kamillenblüten bringt Tanqueray No. 10 Gin eine Explosion von frischen Zitrusfrüchten bei jedem Schluck.",
    "pub_gin_020": "Wenn wir The Botanist destillieren, erschaffen wir mehr als nur ein Getränk. The Botanist ist eine Repräsentation des Ortes, aus dem wir kommen. Es ist eine Art, unseren Platz in der Welt zu kommunizieren und unsere Liebe dafür. Destillieren ist eine Lebensweise, und für mich ist es eine Art, mit der Welt zu kommunizieren. Wir nutzen die Kunst der Destillation und eine Verbindung zum Land, unserer Heimat, um einen wunderbaren Gin zu erschaffen, der die Essenz von Islay ist.",
    "pub_gin_021": "Whitley Neill Gin ist etwas weicher und viel sanfter als traditionelle Gins, mit reichen Noten von Wacholder und Zitrus, Potpourri und exotischen Gewürzen. Der Abgang ist lang mit einem subtilen Nachklang von Kräutern, Kakao und kandierten Zitronenschalen, während die Nase sowohl zitrus-süß als auch pfeffrig ist, mit einem unverwechselbaren blumigen Aroma.",
    "pub_gin_022": "Die Essenz von Rhabarber verleiht unserer weichen Gin-Basis eine herbe, knackige Note, während der Ingwer-Extrakt den Gaumen für einen vollmundigen Abgang wärmt.",
    "pub_gin_023": "Ein handgefertigter Gin von außergewöhnlicher Qualität, der vor süßem Zitrusfruchtgeschmack sizilianischer Blutorangen nur so strotzt. Helle, spritzige Aromen führen einen sauberen Zitrus-Gin an und in jedem Tropfen ein weicher, knackiger Geschmack der mediterranen Sonne.",
    "pub_gin_024": "Eine beliebte Zutat in lokalen Delikatessen — das Zitronengras wurde mit wärmendem Ingwer sowie einer Vielzahl exotischer Kräuter und Gewürze vermischt, was Whitley Neill Lemongrass & Ginger Gin seinen unverwechselbaren, duftenden, zitrusartigen Geschmack verleiht. Ein handgefertigter Gin von außergewöhnlicher Qualität mit einem Geschmack, der so reich ist wie seine Herkunft.",
    "pub_gin_025": "Weiches und rundes Aroma. Noch immer präsenter Wacholder, jetzt gefolgt von bittersüßem, kandiertem Orangengeschmack. Eine dezente, zugrunde liegende blumige Note erhellt die Nase. Kräftige Geschmacksnoten von kandierter Orange, einem Hauch von weißem Pfeffer und einem soliden Rückgrat aus Wacholder. Scheinbar etwas süßer und weicher als das Original. Eine angenehme, ölige Textur kühlt den Mund. Die Orange hält sich durch den Abgang. Wacholder ist immer noch präsent und ergänzt die Zitrusfrüchte. Etwas erdig und holzig.",
    "pub_gin_026": "Ein Vorgeschmack auf den Sommer — süßer und fruchtiger Pfirsich harmoniert wunderbar mit Orangen- und Zitronenanklängen. Frische, süße Pfirsicharomen verbinden sich mit einem Hauch von Zitrus und weichen dann den Anklängen von Wacholder. Im Abgang halten sich süßer Pfirsich und Zitrus mit einem Hauch von pfeffrigem Wacholder am Ende.",
    "pub_gin_027": "Unverwechselbarer Geschmack türkischer Quitte mit einem langen, fruchtigen Abgang. Das Aroma von frischem Steinobst erscheint sofort, sanft gefolgt von Anklängen von Wacholder und Zitrusschale. Der unverwechselbare Geschmack von Quitte dominiert den Gaumen und geht in die Süße von Aprikosen und Pfirsichen über, mit einem langen, fruchtigen Abgang, der sich zu Orangenblüten und spritzigen Grapefruits öffnet.",
    "pub_gin_028": "Unkonventionelle englische Destillation feinster Botanicals, vermischt mit reinstem isländischem Wasser. Ist es Wahnsinn oder Genie? Martin Miller's Original Gin. Ein moderner, klassischer Dry Gin, basierend auf den besten Traditionen englischer Brenner, aber mit unserem eigenen Twist, um den perfekt ausgewogenen Gin zu erhalten.",
    "pub_gin_029": "Dieser Blend nimmt die Form eines Premium-Pink-Gins mit einem lebendigen Erdbeergeschmack und einem weichen Abgang an, der in einem Meer unwiederholbarer Empfindungen endet.",

    # ── SOFT DRINKS ──
    "pub_softdrink_001": "Klassische deutsche Cola mit einem unverwechselbaren Koffein-Kick und ausgewogener Süße.",
    "pub_softdrink_002": "Zuckerfreie Version der klassischen deutschen Cola mit dem gleichen unverwechselbaren Geschmack, gesüßt mit Süßungsmitteln.",
    "pub_softdrink_003": "Klassische deutsche Orangenlimonade, fruchtig und erfrischend.",
    "pub_softdrink_004": "Klassische deutsche Zitronenlimonade, knackig und spritzig.",
    "pub_softdrink_005": "Klassisches deutsches Tafelwasser, reines prickelndes Mineralwasser. Sauber, neutral und erfrischend.",
    "pub_softdrink_006": "Traditionelle deutsche Apfelschorle — halb Apfelsaft, halb Sprudelwasser. Erfrischend und leicht süß.",
    "pub_softdrink_007": "Premium deutsches, klassisches Sprudelmineralwasser mit feiner Perlage.",
    "pub_softdrink_008": "Premium deutsches, natürliches, stilles Mineralwasser. Rein und sauber.",
    "pub_softdrink_009": "Premium Indian Tonic Water, hergestellt mit feinstem Chinin aus dem Kongo und zitrusartigen, botanischen Ölen. Perfekt für Gin & Tonic.",
    "pub_softdrink_010": "Premium Mediterranean Tonic Water, angereichert mit ätherischen Ölen aus mediterraner Zitrone, Thymian und Rosmarin. Aromatisch und erfrischend.",
    "pub_softdrink_011": "Premium Ginger Beer, hergestellt aus einer Mischung von drei Ingwersorten aus Nigeria, Cochin und der Elfenbeinküste. Würzig, wärmend und erfrischend.",
    "pub_softdrink_012": "Premium Ginger Ale mit einem sauberen, erfrischenden Ingwergeschmack. Weniger würzig als Ginger Beer, dafür feiner und ausgewogener.",
    "pub_softdrink_013": "Zartes, rosenaromatisiertes Wasser. Blumig und erfrischend mit einer dezenten Süße.",
    "pub_softdrink_014": "Heidelbeer-aromatisiertes Wasser. Fruchtig und süß mit tiefem Beerencharakter.",
    "pub_softdrink_015": "Pfirsich-aromatisiertes Wasser. Süß und fruchtig mit erfrischendem Charakter.",
    "pub_softdrink_016": "Zitronen-aromatisiertes Wasser. Spritzig und zitrusbetont mit erfrischendem Abgang.",
    "pub_softdrink_017": "Kultige französische Zitruslimonade mit echtem Orangenfruchtfleisch. Süß, spritzig-sauer und sanft prickelnd mit einzigartigem, trübem Aussehen.",
    "pub_softdrink_018": "Orangina-Variante mit roten Früchten. Süße, fruchtige Mischung aus Orangen- und roten Beerenaromen mit der klassischen Fruchtfleisch-Textur.",
    "pub_softdrink_019": "Klassisches Bitter-Lemon-Erfrischungsgetränk. Zitrone und Chinin erzeugen einen erfrischend bittersüßen, knackigen und sauberen Geschmack.",
    "pub_softdrink_020": "Waldbeer-aromatisiertes Erfrischungsgetränk. Fruchtig, süß und erfrischend mit einer Mischung aus Beerenaromen.",
    "pub_softdrink_021": "Reiner deutscher Apfelsaft. Natürlich süß mit einem sauberen, knackigen Apfelgeschmack.",
    "pub_softdrink_022": "Reiner deutscher Orangensaft. Süß, spritzig-sauer und natürlich hell mit reichem Zitrusgeschmack.",
    "pub_softdrink_023": "Reiner Bananensaft. Reichhaltig, cremig und natürlich süß mit authentischem Bananengeschmack.",
    "pub_softdrink_024": "Reiner deutscher Sauerkirschsaft. Herb, fruchtig und tiefgründig mit authentischem Kirschcharakter.",
    "pub_softdrink_025": "Reiner deutscher Johannisbeersaft. Reichhaltig, herb und tief-fruchtig mit intensivem Beerencharakter.",
    "pub_softdrink_026": "Reiner deutscher Tomatensaft. Würzig, reichhaltig und vollmundig mit authentischem Tomatengeschmack.",
    "pub_softdrink_027": "Premium-Cranberrysaft. Herb, fruchtig und erfrischend mit charakteristischer Cranberry-Schärfe.",
    "pub_softdrink_028": "Premium-Yuzu-Limonade. Exotische japanische Zitrusfrucht mit einem einzigartigen, aromatischen und spritzigen Geschmack, erfrischend und raffiniert.",
    "pub_softdrink_029": "Kultiges deutsches Erfrischungsgetränk, das Cola mit Orangesgeschmack kombiniert. Süß, fruchtig und erfrischend mit einem einzigartigen Geschmack.",
    "pub_softdrink_030": "Der kultige Energy Drink, der Flügel verleiht. Süß und spritzig mit einem unverwechselbaren Geschmack und Koffein-Kick.",
    "pub_softdrink_031": "Zuckerfreie Version des kultigen Energy Drinks mit dem gleichen unverwechselbaren Geschmack und Koffein-Kick, gesüßt mit Süßungsmitteln.",

    # ── SPECIAL DRINKS ──
    "pub_special_001": "Guinness und Johannisbeere. Ein klassischer britischer Pub-Mix — reichhaltiges Stout, gemildert durch süße Johannisbeere.",
    "pub_special_002": "2 cl Tia Maria und 2 cl Baileys Irish Cream. Ein geschichteter Shot, der wie ein kleines Pint Guinness aussieht.",
    "pub_special_003": "Jägermeister, in ein Glas Red Bull gegeben. Energetisierender Shot mit Kräuter-Kick.",
    "pub_special_004": "Guinness und Strongbow Cidre. Ein klassischer britischer Pub-Mix — Stout und Cidre ergeben eine weiche, leicht herbe Kombination.",
    "pub_special_005": "Guinness, geschichtet auf Hop House 13 oder Kilkenny. Zwei Biere, die einen auffälligen Schichtungseffekt erzeugen.",
    "pub_special_006": "Brinkhoff's Pils, Strongbow Cidre und Johannisbeere. Ein erfrischender und gefährlich süffiger Pub-Klassiker.",
    "pub_special_007": "Guinness, Baileys Irish Cream und Paddy's Whiskey. Ein reichhaltiger, cremiger Boilermaker, der schnell getrunken werden muss.",
    "pub_special_008": "Baileys, Grand Marnier und Tia Maria, geschichtet in einem Shotglas. Ein klassischer After-Dinner-Shooter.",
    "pub_special_009": "Baileys, Sambuca und Grenadine. Ein süßer, geschichteter Shot mit Anis- und Beerennoten.",
    "pub_special_010": "Baileys, Crème de Menthe und Grand Marnier, geschichtet wie die irische Flagge — grün, weiß und orange.",
    "pub_special_011": "Baileys und Limettensaft. Die Limette lässt die Sahne gerinnen — ein Novelty-Shot mit einzigartiger Textur.",

    # ── SPIRITS ──
    "pub_spirit_001": "Beliebter deutscher Partyschnaps mit kräftigem, wärmendem Charakter.",
    "pub_spirit_002": "Kultiger Berliner Pfefferminzlikör. Kühler, erfrischender Minzcharakter, perfekt als Shot.",
    "pub_spirit_003": "Deutscher Kräuterlikör mit unverwechselbarem, wärmendem Charakter und komplexen Gewürznoten.",
    "pub_spirit_004": "Deutscher Honiglikör. Weich, süß und wärmend mit reichen, blumigen Honignoten.",
    "pub_spirit_005": "Kräftiger, deutscher Kräuterlikör mit kräftigem, wärmendem Charakter. Beliebter Party-Shot.",
    "pub_spirit_006": "Deutscher Haselnusslikör. Süß, nussig und weich mit reichem, geröstetem Haselnussgeschmack.",
    "pub_spirit_007": "Deutscher Maracuja-Likör. Süß, tropisch und fruchtig mit lebendigem Maracuja-Geschmack.",
    "pub_spirit_008": "Traditioneller österreichischer Marillenschnaps. Sauberer, fruchtiger Geist mit hellem Aprikosen-Charakter.",
    "pub_spirit_009": "Traditioneller österreichischer Birnenschnaps. Sauberer, fruchtiger Geist mit hellem Williams-Birnen-Charakter.",
    "pub_spirit_010": "Traditioneller österreichischer Haselnussschnaps. Nussig, weich und wärmend.",
    "pub_spirit_011": "Traditioneller österreichischer Obstschnaps, destilliert aus Äpfeln und Birnen. Sauber, fruchtig und wärmend.",
    "pub_spirit_012": "Klassischer deutscher, doppelt destillierter Kornbrand aus Nordhausen. Sauber, neutral und wärmend.",
    "pub_spirit_013": "Traditioneller Dortmunder Kräuterlikör mit komplexem, botanischem Charakter und wärmendem Abgang.",
    "pub_spirit_014": "Goldener spanischer Likör, hergestellt aus 43 Zutaten, darunter Zitrusfrüchte, Vanille und aromatische Kräuter. Süß, komplex und vielseitig.",
    "pub_spirit_015": "Klassischer italienischer Amaro mit bittersüßem, kräuterigem Profil. Orangenschale, Enzian und andere Botanicals.",
    "pub_spirit_016": "Traditioneller italienischer Zitronenlikör von der Insel Capri. Süß, hell und intensiv zitronig.",
    "pub_spirit_017": "Tropischer Mango-Likör. Süß und spritzig-sauer mit lebendigem Mango-Charakter. Perfekt für Shots oder Cocktails.",
    "pub_spirit_018": "Johannisbeer-Likör. Süß und spritzig-sauer mit tiefem Beeren-Charakter.",
    "pub_spirit_019": "Himbeer-Likör. Süß und spritzig-sauer mit hellem Himbeer-Charakter.",
    "pub_spirit_020": "Likör aus gemischten roten Beeren. Süß und spritzig-sauer mit einer Mischung aus Erdbeere, Himbeere und Johannisbeere.",
    "pub_spirit_021": "Apfel-Likör. Süß und spritzig-sauer mit knackigem, grünem Apfel-Charakter.",
    "pub_spirit_022": "Würziger Shot auf Tomatenbasis mit einem unverwechselbaren Kick. Beliebtes Partygetränk.",
    "pub_spirit_023": "Kultiger italienischer Aperitif mit leuchtend orangefarbenem Ton. Bittersüß mit Noten von Orange, Enzian, Rhabarber und Chinarinde. Perfekt für Aperol Spritz.",
    "pub_spirit_024": "Kultiger italienischer Bitterlikör mit unverwechselbarer roter Farbe. Intensive, kräuterige Bitterkeit, ausgewogen durch süße Orangen- und Kirsch-Noten.",
    "pub_spirit_025": "Premium französischer Orangenlikör. Kristallklar mit einer perfekten Balance aus süßen und bitteren Orangenschalen. Unverzichtbar für Cocktails.",
    "pub_spirit_026": "Schottischer Likör aus gereiftem Scotch Whisky, Heidehonig, Kräutern und Gewürzen. Reichhaltig, süß und wärmend.",

    # ── WHISKIES ──
    "pub_whisky_001": "Weltweit verehrt als der torfigste, rauchigste und komplexeste Single Malt von allen. Doch er stellt den Torf nicht zur Schau, sondern lässt der natürlichen Süße des Malzes den Vortritt, um einen Whisky von perfekter Balance zu erzeugen. Ausgezeichnet als World Whisky of the Year 2008.",
    "pub_whisky_002": "Torfrauch-Wolken und Honigtümpel, geschärft durch Zitronenschale. Unser 12-Jähriger ist sowohl komplex als auch perfekt ausgewogen. Dezente Zitrone und süßer Heidehonig ergänzen Bowmores charakteristischen Torfrauch und führen zu einem köstlichen, langen und milden Abgang.",
    "pub_whisky_003": "Äußerst komplex mit einer Kombination aus süßen, blumigen Düften, Flusskräutern und Blumen mit etwas Honig und Vanille. Ein kräftiger, malziger Geschmack mit Anklängen von süßem Holzrauch und Sandelholz. Ein langer, malzbetonter Abgang mit leichtem Rauch und einem Hauch von Süße.",
    "pub_whisky_004": "Dieser hervorragende, reichhaltig im Sherryfass gereifte Single Malt reift mindestens zwölf Jahre in einer Kombination der feinsten spanischen Pedro-Ximénez- und Oloroso-Sherryfässer. Naturfarben und mit 43 % abgefüllt, ist der Glendronach 12 Jahre alt ein süßer, cremiger Dram.",
    "pub_whisky_005": "Dieser zehn Jahre alte Single Malt ist süß, recht leicht, angenehm, aber mit begrenzter Komplexität. Orangen und brauner Zucker bzw. Karamell, gemischt mit Mokka und gezuckerten Cerealien. Ein wenig Vanille.",
    "pub_whisky_006": "Der Original Malt Whisky Almanac sagt: ,,Ein erstklassiger Malt. Einer der beliebtesten Malts der Welt — und das zu Recht.'' Gereift in traditioneller Eiche, bevor er Zeit in amerikanischen Eichenfässern verbringt, die Vanillenoten verleihen und dem Whisky seine unverwechselbare Weichheit geben.",
    "pub_whisky_007": "Ursprünglich bekannt für seine milden Töne und die Feinheit des Geschmacks. Das Ergebnis ist ein weicher Whisky, der Sie mit einem Schwall von Zitrusfrüchten empfängt und dann mit Schichten von üppigem Geschmack fesselt — von Orange über Honig und cremige Vanille bis hin zu Pfirsich.",
    "pub_whisky_008": "Gebrannt in außergewöhnlich hohen Brennanlagen und zehn Jahre in amerikanischen Weißeichen-Ex-Bourbonfässern gereift. Den letzten Schliff erhält er durch ein Finish in den feinsten gereiften Oloroso-Sherryfässern aus Jerez, Spanien. Ein süßer, weicher Whisky mit reichem, dunklem Schokoladen- und Vanillecreme-Geschmack.",
    "pub_whisky_009": "Perfekt geblendet ist Johnnie Walker Black Label ein reichhaltiger, weicher Scotch Whisky, der ausschließlich aus Single-Malt- und Grain-Whiskys von mehr als 29 Brennereien hergestellt wird, die zwölf Jahre im Fass zu einem lebendigen Geschmackskörper heranreifen.",
    "pub_whisky_010": "Ein klassischer Dram — dieser vollmundige Single Malt hat eine überraschende Süße, die in einen langen, wärmenden Abgang übergeht. Jeder Schluck bringt komplexe Noten von Rauch, Seetang, Torf und einem Hauch von Salz — wie ein belebender Herbsttag an Schottlands rauer Küste.",
    "pub_whisky_011": "Eine Mischung aus Malt Whiskys aus der Speyside-Region (Highland) Schottlands. Die Whiskys werden in kleinen Chargen ausgewählt und dann miteinander vermählt, um in jeder Flasche konstant Monkey Shoulders charakteristischen Geschmack zu erreichen. In der Nase spritzige Orange, Vanille, Honig und Gewürzeiche. Am Gaumen milde Vanille mit würzigen Anklängen.",
    "pub_whisky_012": "Traditionell handwerklich hergestellt mit Techniken, die andere Brennereien längst aufgegeben haben — dieser Gewinner zahlreicher Goldmedaillen bei den renommiertesten internationalen Wettbewerben ist ein Höhepunkt hochwertiger Spirituosen. Trocken, mittelkräftig und weich, reich an Honig und Sahne, dezent salzig mit einer leichten würzigen Note und einem süßen, lang anhaltenden Abgang.",
    "pub_whisky_013": "Whisky aus sowohl Pedro-Ximenez-Oloroso-Seasoned-Fässern als auch nachbefüllten Ex-Bourbonfässern wurde von Hand für seine Honignoten und nussige Intensität ausgewählt. Der Geschmack ist ein Bienenstock voller Aktivität mit weichen Bratäpfeln, üppigem braunem Zucker, einem Hauch von cremigem Kaffee und gerösteten Nussnoten. Eine ambrosische Dekadenz, die es wert ist, genossen zu werden.",
    "pub_whisky_014": "Jura Cask Editions feiern die Verbindung zwischen Land und Geist und bringen unverwechselbare regionale Aromen ausgewählter Fässer aus der ganzen Welt in unseren Insel-Malt. Diese Rumfass-Edition erkundet die Welt der Fass-Finishes aus der Karibik. Dieser wunderbar weiche, aber lebendige Whisky liefert süße Vanille-, Fudge-, Kokosnuss- und würzige tropische Noten.",
    "pub_whisky_015": "Reichhaltig mit Zitruscharakter. Traditionelle Eichen- und abgelagerte Sherryfässer werden beide mit großer Wirkung eingesetzt, da die darin gereiften Spirituosen zu einem dezent ausgewogenen Geschmack vereint werden.",
    "pub_whisky_016": "Eingeführt 1993 nach einem Verfahren, das unser Malt Master David Stewart 1982 entwickelte — heute allgemein als ,,Wood Finishing'' bekannt. Der Balvenie DoubleWood Single Malt Whisky gewinnt seinen unverwechselbaren Charakter durch die Reifung in zwei verschiedenen Holzarten. Jede Stufe verleiht dem resultierenden Single Malt unterschiedliche Qualitäten.",
    "pub_whisky_017": "Ausgesprochen ,,Oog-a-dal'', ist es eine besondere Vermählung, die Ardbegs traditionelle tiefe, rauchige Noten mit üppigen, rosinigen Tönen alter Ex-Sherryfässer verbindet. Ardbeg Uigeadail wurde von den über 120.000 Mitgliedern des Ardbeg Committee zu ihrem Lieblings-Ardbeg gewählt. Vollmundig und reichhaltig mit einer tiefen, den Mund umhüllenden Textur — der Geschmack ist eine faszinierende Balance zwischen süßen, würzigen und tiefrauchigen Aromen. Wellen tiefer Rauchtöne und reicher Aromen bauen sich am Gaumen auf wie eine feine Montecristo-Zigarre.",
    "pub_whisky_018": "Reichhaltige Rosinen und sanfter Rauch führen zu einem köstlichen, schokoladigen Kern. Zuerst in Bourbonfässern, dann in Oloroso-Fässern gereift — es gibt kein besseres Beispiel für ein Sherry-Fass-Finish als unseren 15-Jährigen. Es sind die letzten drei Jahre in Oloroso-Sherryfässern, die Bowmore 15 Years Old die reiche, tiefe Farbe und den robusten, wärmenden Abgang verleihen.",
    "pub_whisky_019": "Im Solera-Verfahren gereift, ist er ein köstlicher Single Malt mit feinen Extrakten von Honig und Vanille. Er reift in Oloroso-Sherry-, Bourbon- und neuen Eichenfässern. Durch diese verschiedenen Fasstypen entwickeln sich feine Aromen, die wunderschön integriert und frisch sind.",
    "pub_whisky_020": "Sehr aromatisch und blumig, wie das Einatmen eines ländlichen Gartens. Deutliche Vanille, Schnittblumen — Narzissen, Blüten und Lilienanklänge — und darunter eine saubere, röstige Note. Wird zunehmend süß und cremig mit einem leicht aromatischen Rand und frischer Zitrusfrucht.",
    "pub_whisky_021": "Beginnt mit unseren giraffenhöhen Brennanlagen, die einen köstlich zarten und fruchtigen Geist erzeugen. Anschließend reift er zwölf Jahre in Bourbon- und Sherryfässern und verwandelt sich in eine mundwässernde Odyssee voller reicher Würze und sonnenverwöhnter Süße.",
    "pub_whisky_022": "Unsere charakteristische Abfüllung und der definitive Bruichladdich. Er zeigt den klassischen, blumigen und eleganten Bruichladdich-Hausstil. The Classic Laddie wird aus 100 % schottischer Gerste hergestellt, tröpfchenweise destilliert, nicht kaltfiltriert und ohne Farbstoff.",
    "pub_whisky_023": "Eine Whisky-Reise ins Wilde — ein dunkler und köstlicher Wald, in dem der Wind mit Böen von Pfefferminze pfeift und jederzeit dunkle Schokoladenwirbel auftreten können. In unseren giraffenhöhen Brennanlagen beginnt er weich und fruchtig, wird dann dunkler und tiefer, während wir ihn 14 Jahre in Bourbonfässern und Portweinfässern aus Portugal reifen lassen. Der fertige Whisky ist ein Dickicht üppiger Geschmackskombinationen — Walnuss und schwarzer Pfeffer, Mandarinenorange und geschmolzener Marshmallow, dunkle Schokolade und Pfefferminze.",
    "pub_whisky_024": "Unser kultiger 12 Jahre alter Single Malt Whisky ist würzig und rund, vollgepackt mit den Aromen sonnenverwöhnter Bitterorangen und reichhaltigem Früchtekuchen, gewürzt mit Zimt, Muskatnuss und Nelken. Sie finden flüssigen Heidehonig in den Wellen heidigen Torfrauchs.",
    "pub_whisky_025": "Dieser zwölf Jahre alte Single Malt hat viel Sherry und Honig in der Nase. Es gibt dezente Anklänge von Gewürz, Eiche und Rauch. Ein schöner, mittelkräftiger Schluck. Die Sherry-Süße kommt sofort durch, mit weiteren Noten von Früchtekuchen, Rosinen, Eiche und Gewürz. Der Zwölfjährige ist kein komplexer Whisky, aber die Aromen sind wunderschön ausgewogen.",
    "pub_whisky_026": "Benannt nach einer Bucht an Islays rauer Atlantikküste, ist Sanaig eine Vermählung von Sherry- und Bourbonfässern. Der hohe Anteil an Oloroso-Sherry-Einfluss verleiht eine Balance aus getrockneten Früchten und Gewürzen zum klassischen Kilchoman-Charakter aus Zitrussüße und Torfrauch.",
    "pub_whisky_027": "Wir freuen uns, bekannt zu geben, dass Harveys Lewes Blend Whisky es in Jim Murrays Whisky Bible 2016 geschafft hat. Mit 89,5/100 bewertet, beschrieb Murray ihn als ,,einen hervorragenden Whisky von einer Perle einer Brauerei''. Vor über hundert Jahren mischte und füllte Harveys Brewery verschiedene Spirituosen ab, darunter Lewes Blend Whisky. Ein Jahrhundert später feiert diese Fortführung des ursprünglichen Blends unsere anhaltende Leidenschaft für feinste Spirituosen.",
    "pub_whisky_028": "Aromen von Orangenschale, Rauch, Meersalz und Honig zeichnen diesen vollmundigen Highland Malt aus.",
    "pub_whisky_029": "Eine Ode an unsere kleinste, aber wichtigste Brennanlage, die ,,Wee Witchie''. Dieser zwölf Jahre alte Single Malt Scotch Whisky wurde doppelfassgereift — sowohl in europäischer als auch amerikanischer Eiche — um den unverwechselbar reichen und robusten Charakter zu verstärken, der Mortlach-Whiskys legendär macht.",
    "pub_whisky_030": "Mild, golden und süßrauchig — Caol Ila 18 Years Old erinnert an die Sonne, die tief über den sterbenden Gluten eines Strandlagerfeuers versinkt, während der Tag sanft in die Dunkelheit der schließenden Nacht übergeht. Der verborgene Schatz von Islay. Ausgesprochen ,,Cull Eela'', ist es der gälische Name für den Sund von Islay. Feiner, rauchiger Whisky, produziert von Generationen von Inselbewohnern.",
    "pub_whisky_031": "Mindestens 16 Jahre in Eichenfässern gereift, hat dieser begehrte Single Malt den massiven Torfrauch-Geschmack, der für den Süden Islays typisch ist, und bietet gleichzeitig eine Reichhaltigkeit und Trockenheit, die ihn zu einem wirklich interessanten Dram macht.",
    "pub_whisky_032": "Gereift in First-Fill-Sherry-gereiften europäischen und amerikanischen Eichenfässern, zollt dieser hervorragende 18-jährige Single Malt unseren fünf Grundpfeilern der Produktion Tribut und präsentiert ein raffiniertes Medley aus reifen Kirschen, bestäubt mit bittersüßem Kakao, frisch geernteten Honigwaben und kandierter Orangenschale. Ein Hauch von Orkneys salziger Meeresgischt im aromatischen Torfrauch.",
    "pub_whisky_033": "Die Distillers Edition ist eine Kollektion von Meisterhandwerk. Jedes Fass der Serie wird individuell ausgewählt und perfekt auf den Charakter jedes der hier veredelten Single Malts abgestimmt. Der zweigeteilte Reifeprozess verleiht mehr Tiefe und Komplexität — die Idee hinter der limitierten Distillers Edition: die Perfektion der Single Malts zu bewahren und gleichzeitig ausgewählte Geschmacksnuancen stärker zu akzentuieren.",
    "pub_whisky_034": "Dieser 15 Jahre gereifte Mortlach Single Malt Scotch Whisky wird in einer metallisch-goldenen Dose präsentiert, die eine detailreiche Federzeichnung des Dreiäugigen Raben zeigt, wie er in den acht Staffeln der Serie zu sehen war. Die Six Kingdoms-Verpackung ist eine Hommage an den letzten Grünseher. Mortlachs charakteristische 2,81-fach-Destillation ist ein komplexer Prozess, so einzigartig wie der Dreiäugige Rabe selbst.",
    "pub_whisky_035": "Mit wunderbarer Süße und Wärme, durchwoben von einem Hauch Rauch, ist Talisker 18 Year Old ein preisgekrönter Whisky, der reichhaltig und weich, aber dennoch durchsetzungsfähig ist. Ausgezeichnet als ,,Bester Single Malt Whisky der Welt 2007'' bei den World Whiskies Awards, ist Talisker 18 Year Old ein Single-Malt-Meisterwerk.",
    "pub_whisky_036": "Geschaffen zur Feier der Krönung Ihrer Majestät Königin Elizabeth II. — in jedem Maß stecken Geschichte und Vermächtnis. Eine königliche Hommage, die britisch bis ins Mark ist. Geschaffen als Geschenk für eine neue Königin, ist The Signature Blend raffiniert und opulent im Charakter. Das Ergebnis einer Auswahl seltener und außergewöhnlicher Scotch Whiskys, die mindestens 21 Jahre gereift sind — das unglaublich reiche und elegante Profil verleiht jeder Feier einen Hauch königlicher Raffinesse.",
    "pub_whisky_037": "Über den Verlauf von 18 Jahren führt unser Master Distiller Alan Winchester diese Abfüllung durch eine Kombination von Fasstypen — sowohl First- als auch Second-Fill-Amerikanische Eiche für tropische Fruchtigkeit als auch Ex-Sherry-Eiche für würzige Komplexität. Das Ergebnis dieser geschickten Navigation der Destillationskunst ist ein wunderschöner Single Malt Scotch Whisky, der komplex, aber elegant und ausgewogen ist. The Glenlivet 18 Year Old hat mehr Preise gewonnen als jede andere Abfüllung.",
    "pub_whisky_038": "Dieser Single Malt Scotch Whisky ist inspiriert von der kultigen und lohnenden Erstabfüllung des 16-Jährigen von 1992. Er wurde ausschließlich in Sherryfässern gereift, um reiche, fruchtige und duftende Noten auf der für Mortlach typischen bestialischen Komplexität zu verleihen.",
    "pub_whisky_039": "Wir vermählen unseren 18-Jährigen in kleinen Chargen von höchstens 150 Fässern. Jede Charge ist individuell nummeriert und sorgfältig überwacht. Jede hat außergewöhnliche Konsistenz und Charakter durch eine intensive Vermählungszeit und einen wärmenden, distinguierten Abgang. Nase: Ein bemerkenswert reiches Aroma mit reifer Obstgartenfrucht, Bratapfel und robuster Eiche. Geschmack: Liefert reichhaltig üppige Trockenfrüchte, kandierte Schale und Datteln, überlagert mit eleganten Eichennoten.",
    "pub_whisky_040": "Unser Bushmills 10 Year Old ist eine Vermählung von Single Malts, die mindestens zehn Jahre in handverlesenen Bourbonfässern und Sherry-Butts gereift sind. Spritzig und frisch in der Nase, gefolgt von Noten reifer Früchte, cremiger Vanille und weichem, getoastetem Holz.",
    "pub_whisky_041": "Black Bush kombiniert einen hohen Anteil an Single Malt Whiskey, der in ehemaligen Oloroso-Sherryfässern gereift ist, mit einem süßen, chargenweise destillierten Grain Whiskey. Dieses einzigartige Rezept verleiht Black Bush reiche, fruchtige Noten und einen tiefen, intensiven Charakter, ausgewogen durch eine unglaublich einzigartige Weichheit.",
    "pub_whisky_042": "Der Grundpfeiler unserer Familie — Bushmills Original ist ein weicher und vielseitiger, dreifach destillierter Blend. Ein zugänglicher Whiskey, der sowohl in Bourbon- als auch Sherryfässern gereift ist und frische Frucht- und Vanillenoten bietet.",
    "pub_whisky_043": "Ein leichter, blumiger Duft, gepfeffert mit würzigen Holz- und süßen Noten. Die perfekte Balance aus würzigen, nussigen und Vanillenoten mit Anklängen von süßem Sherry und außergewöhnlicher Weichheit.",
    "pub_whisky_044": "Es gibt einen Grund, warum Paddy seit fast einem Vierteljahrtausend auf die gleiche Weise in County Cork, Irland, dreifach destilliert wird. Manche guten Dinge finden kein Ende. In der Nase ist er malzig, frisch und holzig mit Anklängen von Gewürz, Honig und Vanille. Der Geschmack ist leicht und knackig mit Anklängen von Nüssen, Malz und verkohltem Holz.",
    "pub_whisky_045": "Tullamore Dew ist der originale Triple-Blend-Irish-Whiskey, weltweit bekannt für seine weiche und sanfte Komplexität. Die komplexen, aber zugänglichen Aromen im Whiskey stammen aus drei Getreidesorten, dreifacher Destillation und der Mischung aller drei Irish-Whiskey-Arten.",
    "pub_whisky_046": "Mischen Sie Ihren Lieblingscocktail mit einem raffinierten, zeitgenössischen Flair mit diesem weltweiten Favoriten. Genießen Sie diesen weichen und milden Bourbon mit seinem langen und sanften Abgang. 80 Proof, 40 % Alkohol.",
    "pub_whisky_047": "Tropfen für Tropfen durch drei Meter Zuckerahorn-Holzkohle gefiltert, dann in handgefertigten Fässern unserer eigenen Herstellung gereift. Und unser Tennessee Whiskey folgt keinem Kalender — er ist erst fertig, wenn unsere Verkoster sagen, dass er es ist. Wir beurteilen ihn nach seinem Aussehen, nach seinem Aroma und natürlich nach seinem Geschmack. So hat es Jack Daniel selbst vor über einem Jahrhundert gemacht. Und so machen wir es noch heute.",
    "pub_whisky_048": "Elegant, weich, raffiniert. Das bewirken vier Jahre Reifung in frisch verkohlten amerikanischen Weißeichenfässern bei unserem Bourbon. Aber jeder Tropfen ist die Mühe wert, und wir lieben die Idee, am Rezept unseres Ururgroßvaters festzuhalten.",
    "pub_whisky_049": "Wir nehmen die Flüssigkeit, die wir aus unseren Fässern extrahieren, mischen sie mit extra-gereiftem Kentucky Straight Bourbon Whiskey und füllen sie mit 90 Proof ab, um einen Premium-Bourbon mit zusätzlicher Tiefe und Komplexität zu schaffen. Konzipiert, um pur oder On the Rocks genossen zu werden, hat Jim Beam Devil's Cut einen robusten Geschmack mit tiefer Farbe, Aroma und Charakter.",
    "pub_whisky_050": "Wenn es darum geht, Knob Creek Bourbon herzustellen, gibt es viel zu warten, aber kaum Zeit zum Herumsitzen. Während jedes Fass geduldig in Weißeiche reift, erhöhen unsere Brenner weiterhin die Standards und erfüllen ihr Engagement für vollen Geschmack. Das Ergebnis ist eine unerschütterliche Balance aus tiefem Bourbon im Pre-Prohibition-Stil mit robustem Eichengeschmack, ergänzt durch weiche Vanille und geschichtetes Karamell.",
    "pub_whisky_051": "Manchmal ist es eine gute Sache, Feuer und Whiskey zu mischen. Unser Tennessee Fire vereint warmen Zimtlikör mit dem kräftigen Charakter von Jack Daniel's Old No. 7 zu einem klassischen Geist mit einem überraschend warmen Abgang.",
    "pub_whisky_052": "Hat den einzigartigen Charakter von Jack Daniel's Tennessee Whiskey, gepaart mit knackigem, grünem Apfel für einen frischen und lohnenden Geschmack. Er ist kräftig, erfrischend und außergewöhnlich weich.",
    "pub_whisky_053": "Wir präsentieren Rye Whiskey, hergestellt auf Jacks Art. Gefertigt mit unserer 70-prozentigen Roggen-Getreidemischung, natürlichem Quellwasser aus unserer eigenen Cave Spring Hollow und Jacks bewährtem Holzkohle-Mellowing-Verfahren — Jack Daniel's Tennessee Rye ist ein Whiskey, der nur aus Lynchburg, Tennessee, kommen kann.",
    "pub_whisky_054": "Mit 94 Proof abgefüllt, schichtet Single Barrel Select dezente Noten von Karamell und Gewürz mit hellen Fruchtnoten und süßen Aromen zu einem Tennessee Whiskey mit einzigartigem Geschmack.",
    "pub_whisky_055": "Die Kunst, feinen Bourbon herzustellen, fand erstmals 1812 auf dem Gelände der Woodford Reserve Distillery statt, einem National Historic Landmark. Der perfekt ausgewogene Geschmack unseres Kentucky Straight Bourbon Whiskey besteht aus mehr als 200 nachweisbaren Geschmacksnoten — von kräftigem Getreide und Holz bis zu süßen Aromen, Gewürzen sowie Frucht- und Blumennoten.",
}

# Process all files
for fpath in sorted(glob.glob(f"{OUT}/*.json")):
    with open(fpath) as f:
        d = json.load(f)
    did = d["id"]
    if did in NOTES_DE:
        d["notes_de"] = NOTES_DE[did]
    with open(fpath, "w") as f:
        json.dump(d, f, indent=2, ensure_ascii=False)

# Count
done = sum(1 for did in NOTES_DE)
total = len(glob.glob(f"{OUT}/*.json"))
print(f"Translated {done}/{total} files ({done*100//total}%)")
remaining = total - done
if remaining:
    ids_left = [d for d in sorted(glob.glob(f"{OUT}/*.json")) if json.load(open(d))["id"] not in NOTES_DE]
    print(f"Still need translation: {remaining}")
    for p in ids_left:
        d = json.load(open(p))
        print(f"  {d['id']}: {d['name']}")
